export const authCopy = {
  fa: {
    brand: 'ویانور',
    home: 'بازگشت به ویانور',
    eyebrow: 'فضایی برای رشد و گفت‌وگو',
    hero: 'با آرامش وارد شوید؛\nمسیر شما از اینجا آغاز می‌شود.',
    intro: 'یک حساب برای پیگیری مسیر شخصی شما در ویانور.',
    privacy: 'رمز شما به‌صورت هش‌شده نگهداری می‌شود.',
    email: 'نشانی ایمیل',
    password: 'رمز عبور',
    confirm: 'تکرار رمز عبور',
    show: 'نمایش رمز',
    hide: 'پنهان کردن رمز',
    hint: 'حداقل ۱۵ و حداکثر ۱۲۸ نویسه؛ یک عبارت طولانی و یکتا انتخاب کنید.',
    login: 'ورود به حساب',
    register: 'ساخت حساب',
    forgot: 'بازیابی رمز عبور',
    reset: 'انتخاب رمز جدید',
    verify: 'تأیید ایمیل',
    resend: 'ارسال دوبارهٔ لینک تأیید',
    submit: 'ادامه',
    busy: 'در حال انجام…',
    newHere: 'حساب ندارید؟',
    haveAccount: 'قبلاً ثبت‌نام کرده‌اید؟',
    forgotLink: 'رمز را فراموش کرده‌اید؟',
    sent: 'اگر این نشانی واجد شرایط باشد، ایمیل راهنما ارسال می‌شود. پوشهٔ هرزنامه را هم بررسی کنید.',
    verified: 'ایمیل شما تأیید شد. اکنون وارد شوید.',
    resetDone: 'رمز تغییر کرد و نشست‌های قبلی باطل شدند. با رمز جدید وارد شوید.',
    mismatch: 'تکرار رمز با رمز عبور یکسان نیست.',
    missingToken: 'لینک معتبر در این صفحه پیدا نشد؛ لینک ایمیل را باز کنید یا درخواست جدید بدهید.',
    verifyHint: 'برای تأیید نشانی ایمیل، دکمهٔ زیر را بزنید.',
    security: 'امنیت حساب',
    securityIntro: 'نشست‌های فعال حساب خود را ببینید و دسترسی دستگاه‌ها را پایان دهید.',
    sessions: 'نشست‌های فعال',
    current: 'این نشست',
    session: 'نشست',
    created: 'زمان ورود',
    expires: 'پایان اعتبار',
    revoke: 'پایان این نشست',
    revokeAll: 'پایان همهٔ نشست‌ها',
    confirmRevoke: 'آیا می‌خواهید همهٔ نشست‌ها، از جمله این نشست، پایان یابند؟',
    logout: 'خروج',
    refresh: 'تازه‌سازی نشست',
    loading: 'در حال بررسی حساب…',
    loginRequired: 'برای مشاهدهٔ امنیت حساب وارد شوید.',
    account: 'حساب شما',
    gallery: 'دیدن قالب داشبوردها',
    demo: 'قالب داشبوردها همچنان با دادهٔ نمونه نمایش داده می‌شود.',
    language: 'English',
    footer: 'ورود با ایمیل • مدیریت نشست • ارتباط امن',
    errors: {
      INVALID_INPUT: 'اطلاعات واردشده معتبر نیست. نشانی ایمیل و طول رمز را بررسی کنید.',
      INVALID_CREDENTIALS: 'ورود ممکن نشد. اطلاعات ورود و تأیید ایمیل را بررسی کنید.',
      INVALID_TOKEN: 'این لینک معتبر نیست، منقضی شده یا قبلاً استفاده شده است.',
      RATE_LIMITED: 'تعداد تلاش‌ها زیاد است. کمی بعد دوباره امتحان کنید.',
      NOT_CONFIGURED: 'ورود هنوز روی این نصب تنظیم نشده است.',
      UNAVAILABLE: 'ارتباط با سرویس برقرار نشد. دوباره تلاش کنید.',
      BUSY: 'سرویس در حال پاسخ‌گویی به درخواست‌های دیگر است. دوباره تلاش کنید.',
      FORBIDDEN: 'درخواست تأیید نشد. صفحه را از نشانی اصلی سایت باز کنید.',
    },
  },
  en: {
    brand: 'Vianoor',
    home: 'Back to Vianoor',
    eyebrow: 'A space to grow and connect',
    hero: 'A calmer beginning.\nYour journey starts here.',
    intro: 'One account for your personal journey with Vianoor.',
    privacy: 'Your password is stored as a secure hash.',
    email: 'Email address',
    password: 'Password',
    confirm: 'Confirm password',
    show: 'Show password',
    hide: 'Hide password',
    hint: 'Use 15–128 characters. Choose a long, unique passphrase.',
    login: 'Sign in',
    register: 'Create an account',
    forgot: 'Recover your password',
    reset: 'Choose a new password',
    verify: 'Verify your email',
    resend: 'Resend verification link',
    submit: 'Continue',
    busy: 'Working…',
    newHere: 'New to Vianoor?',
    haveAccount: 'Already have an account?',
    forgotLink: 'Forgot your password?',
    sent: 'If this address is eligible, an email will arrive with instructions. Check your spam folder too.',
    verified: 'Your email is verified. You can now sign in.',
    resetDone:
      'Your password was changed and previous sessions revoked. Sign in with your new password.',
    mismatch: 'The passwords do not match.',
    missingToken: 'No valid link was found. Open the link in your email or request a new one.',
    verifyHint: 'Press the button below to verify your email address.',
    security: 'Account security',
    securityIntro: 'Review your active sessions and end access on your devices.',
    sessions: 'Active sessions',
    current: 'This session',
    session: 'Session',
    created: 'Signed in',
    expires: 'Expires',
    revoke: 'End this session',
    revokeAll: 'End all sessions',
    confirmRevoke: 'End all sessions, including this one?',
    logout: 'Sign out',
    refresh: 'Refresh session',
    loading: 'Checking your account…',
    loginRequired: 'Sign in to view your account security.',
    account: 'Your account',
    gallery: 'Explore dashboard previews',
    demo: 'Dashboard previews still display sample data.',
    language: 'فارسی',
    footer: 'Email sign-in • Session management • Secure connection',
    errors: {
      INVALID_INPUT: 'Please check your email address and password length.',
      INVALID_CREDENTIALS: 'Unable to sign in. Check your credentials and email verification.',
      INVALID_TOKEN: 'This link is invalid, expired or already used.',
      RATE_LIMITED: 'Too many attempts. Please try again later.',
      NOT_CONFIGURED: 'Sign-in is not configured on this installation yet.',
      UNAVAILABLE: 'Unable to reach the service. Please try again.',
      BUSY: 'The service is busy. Please try again.',
      FORBIDDEN: 'The request was not accepted. Open the site at its official address.',
    },
  },
};
