import { createDictionary } from './localization-runtime';
export const communicationCopy = createDictionary('communicationCopy', {
  en: {
    title: 'Messages and notifications',
    messages: 'Messages',
    channels: 'Expert channels',
    questions: 'Questions and answers',
    notifications: 'Notifications',
    support: 'Contact support',
    inbox: 'Managed inbox',
    newMessage: 'New message',
    send: 'Send',
    reply: 'Reply',
    cancel: 'Cancel',
    refresh: 'Refresh',
    loadMore: 'Load more',
    empty: 'No records yet.',
    choose: 'Choose a conversation',
    closed: 'This conversation is archived.',
    typing: 'Typing…',
    ONLINE: 'Online',
    AWAY: 'Away',
    OFFLINE: 'Offline',
    SENT: 'Sent',
    DELIVERED: 'Delivered',
    READ: 'Read',
    BOOKING: 'Session chat',
    CONSULTATION: 'Text consultation',
    SUPPORT: 'Support',
    CHANNEL_INBOX: 'Channel inbox',
    QUESTION: 'Question',
    OPEN: 'Open',
    ARCHIVED: 'Archived',
    category: 'Category',
    claim: 'Open for review',
    forward: 'Forward to expert',
    archive: 'Archive',
    reopen: 'Reopen',
    save: 'Save',
    body: 'Message',
    attachment: 'Attach a file',
    record: 'Record voice',
    stop: 'Stop recording',
    recordHint: 'Recording starts only after microphone permission. Maximum 10 minutes.',
    filePending: 'The file is being scanned. Please wait.',
    download: 'Open attachment',
    error: 'The action could not be completed. Try again.',
    success: 'Saved.',
    noAccess: 'You do not have access to this conversation.',
    contextHint:
      'Private conversations are opened from an eligible booking or an assigned question.',
    follow: 'Follow',
    unfollow: 'Unfollow',
    channelTitle: 'Channel title',
    description: 'Description',
    commentsEnabled: 'Allow moderated comments',
    createChannel: 'Save my channel',
    post: 'Publish post',
    remove: 'Remove',
    comments: 'Comments',
    addComment: 'Submit comment for review',
    approve: 'Approve',
    reject: 'Reject',
    PENDING: 'Pending review',
    APPROVED: 'Approved',
    REJECTED: 'Rejected',
    sendToChannel: 'Message channel administrators',
    channelHint:
      'Following does not grant private chat access. Inbox messages reach the expert only after administrative review.',
    ask: 'Submit a private question',
    answer: 'Answer',
    assign: 'Assign expert',
    expertCode: 'Expert public ID',
    PRIVATE: 'Private',
    PUBLIC: 'Public with public ID',
    ANONYMOUS: 'Anonymous public copy',
    visibility: 'Publication choice',
    publicQuestion: 'Public question text',
    publicAnswer: 'Public answer text',
    publicationHint:
      'Only this separate copy is published after your consent and review. Remove names and private details for anonymous publication.',
    publish: 'Approve publication',
    conversation: 'Open conversation',
    preferences: 'Notification preferences',
    email: 'Email',
    sms: 'SMS',
    BOOKINGS: 'Bookings',
    MESSAGES: 'Messages',
    PAYMENTS: 'Payments',
    MARKETING: 'Promotions',
    markRead: 'Mark read',
    phone: 'Phone number with country code',
    code: 'Verification code',
    sendCode: 'Send verification code',
    verify: 'Verify phone',
    verified: 'Phone verified',
    smsUnavailable: 'SMS is unavailable until the administrator configures a provider.',
    smsSettings: 'SMS connection',
    account_sid: 'Twilio account SID',
    auth_token: 'Twilio auth token',
    messaging_service_sid: 'Messaging service SID',
    verify_service_sid: 'Verify service SID',
    enabled: 'Enabled',
    credentialsHint:
      'Credentials are encrypted and never returned. Save without credentials to change only availability.',
    NEW_MESSAGE: 'New message',
    INBOX_FORWARDED: 'Channel message forwarded',
    CHANNEL_POST: 'New channel post',
    PAYMENT_COMPLETED: 'Payment completed',
    CONFIRMED: 'Booking confirmed',
    CANCELLED: 'Booking cancelled',
    COMPLETED: 'Session completed',
    REMINDER_1440: 'Session reminder: 24 hours',
    REMINDER_60: 'Session reminder: 1 hour',
    REMINDER_10: 'Session reminder: 10 minutes',
    settings: 'Settings',
    moderation: 'Moderation',
    status: 'Status',
    publicList: 'Published questions',
    more: 'More',
    link: 'Open link',
    recording: 'Recording',
    fileReady: 'Attachment ready',
    clearFile: 'Remove attachment',
    unread: 'Unread',
  },
  fa: {
    title: 'پیام‌ها و اعلان‌ها',
    messages: 'پیام‌ها',
    channels: 'کانال استادان',
    questions: 'پرسش و پاسخ',
    notifications: 'اعلان‌ها',
    support: 'ارتباط با پشتیبانی',
    inbox: 'صندوق مدیریت',
    newMessage: 'پیام جدید',
    send: 'ارسال',
    reply: 'پاسخ به پیام',
    cancel: 'انصراف',
    refresh: 'تازه‌سازی',
    loadMore: 'نمایش بیشتر',
    empty: 'هنوز موردی ثبت نشده است.',
    choose: 'یک مکالمه انتخاب کنید',
    closed: 'این مکالمه بایگانی شده است.',
    typing: 'در حال نوشتن…',
    ONLINE: 'آنلاین',
    AWAY: 'دور از دسترس',
    OFFLINE: 'آفلاین',
    SENT: 'ارسال شد',
    DELIVERED: 'تحویل شد',
    READ: 'خوانده شد',
    BOOKING: 'گفت‌وگوی جلسه',
    CONSULTATION: 'مشاوره متنی',
    SUPPORT: 'پشتیبانی',
    CHANNEL_INBOX: 'صندوق کانال',
    QUESTION: 'پرسش',
    OPEN: 'باز',
    ARCHIVED: 'بایگانی',
    category: 'دسته‌بندی',
    claim: 'باز کردن برای بررسی',
    forward: 'ارجاع به استاد',
    archive: 'بایگانی',
    reopen: 'بازگشایی',
    save: 'ذخیره',
    body: 'متن پیام',
    attachment: 'پیوست فایل',
    record: 'ضبط پیام صوتی',
    stop: 'پایان ضبط',
    recordHint: 'ضبط فقط با اجازهٔ میکروفن شروع می‌شود؛ حداکثر ۱۰ دقیقه.',
    filePending: 'فایل در حال بررسی امنیتی است؛ کمی صبر کنید.',
    download: 'باز کردن پیوست',
    error: 'انجام این کار ممکن نشد؛ دوباره تلاش کنید.',
    success: 'ذخیره شد.',
    noAccess: 'به این مکالمه دسترسی ندارید.',
    contextHint: 'گفت‌وگوی خصوصی از رزرو مجاز یا پرسش تخصیص‌یافته باز می‌شود.',
    follow: 'دنبال کردن',
    unfollow: 'لغو دنبال کردن',
    channelTitle: 'عنوان کانال',
    description: 'توضیحات',
    commentsEnabled: 'پذیرش نظر با بررسی',
    createChannel: 'ذخیره کانال من',
    post: 'انتشار پست',
    remove: 'حذف',
    comments: 'نظرها',
    addComment: 'ارسال نظر برای بررسی',
    approve: 'تأیید',
    reject: 'رد',
    PENDING: 'در انتظار بررسی',
    APPROVED: 'تأیید شده',
    REJECTED: 'رد شده',
    sendToChannel: 'پیام به مدیریت کانال',
    channelHint:
      'دنبال کردن کانال مجوز چت خصوصی نمی‌دهد. پیام صندوق پس از بررسی مدیر به استاد می‌رسد.',
    ask: 'ثبت پرسش خصوصی',
    answer: 'پاسخ',
    assign: 'تخصیص استاد',
    expertCode: 'شناسه عمومی استاد',
    PRIVATE: 'خصوصی',
    PUBLIC: 'عمومی با شناسه عمومی',
    ANONYMOUS: 'نسخه عمومی ناشناس',
    visibility: 'انتخاب انتشار',
    publicQuestion: 'متن عمومی پرسش',
    publicAnswer: 'متن عمومی پاسخ',
    publicationHint:
      'فقط این نسخه جداگانه پس از رضایت شما و بررسی منتشر می‌شود. برای انتشار ناشناس، نام‌ها و اطلاعات خصوصی را حذف کنید.',
    publish: 'تأیید انتشار',
    conversation: 'باز کردن مکالمه',
    preferences: 'تنظیمات اعلان',
    email: 'ایمیل',
    sms: 'پیامک',
    BOOKINGS: 'رزروها',
    MESSAGES: 'پیام‌ها',
    PAYMENTS: 'پرداخت‌ها',
    MARKETING: 'تبلیغات',
    markRead: 'خوانده شد',
    phone: 'شماره تلفن با پیش‌شماره کشور',
    code: 'کد تأیید',
    sendCode: 'ارسال کد تأیید',
    verify: 'تأیید شماره',
    verified: 'شماره تأیید شده',
    smsUnavailable: 'پیامک پس از تنظیم ارائه‌دهنده توسط مدیر فعال می‌شود.',
    smsSettings: 'اتصال پیامک',
    account_sid: 'شناسه حساب Twilio',
    auth_token: 'کلید اتصال Twilio',
    messaging_service_sid: 'شناسه سرویس پیامک',
    verify_service_sid: 'شناسه سرویس تأیید شماره',
    enabled: 'فعال',
    credentialsHint:
      'اطلاعات اتصال رمز می‌شود و دوباره نمایش داده نمی‌شود. برای تغییر وضعیت، فیلدهای اتصال را خالی بگذارید.',
    NEW_MESSAGE: 'پیام جدید',
    INBOX_FORWARDED: 'پیام کانال به شما ارجاع شد',
    CHANNEL_POST: 'پست جدید کانال',
    PAYMENT_COMPLETED: 'پرداخت تکمیل شد',
    CONFIRMED: 'رزرو تأیید شد',
    CANCELLED: 'رزرو لغو شد',
    COMPLETED: 'جلسه پایان یافت',
    REMINDER_1440: 'یادآوری جلسه: ۲۴ ساعت',
    REMINDER_60: 'یادآوری جلسه: یک ساعت',
    REMINDER_10: 'یادآوری جلسه: ۱۰ دقیقه',
    settings: 'تنظیمات',
    moderation: 'بررسی پیام‌ها',
    status: 'وضعیت',
    publicList: 'پرسش‌های منتشرشده',
    more: 'بیشتر',
    link: 'باز کردن پیوند',
    recording: 'در حال ضبط',
    fileReady: 'پیوست آماده است',
    clearFile: 'حذف پیوست',
    unread: 'خوانده‌نشده',
  },
});
