export const copy = {
  fa: {
    brand: 'ویانور',
    tagline: 'همراهِ روشنِ زندگی',
    language: 'English',
    skip: 'رفتن به محتوای اصلی',
    intro: 'فضایی برای پرسیدن، شنیده‌شدن و پیدا کردن راهی روشن‌تر؛ در کنار همراهانی آگاه.',
    eyebrow: 'با آگاهی، آرام‌تر قدم بردارید',
    hero1: 'برای هر پرسش،',
    hero2: 'یک همراهِ روشن.',
    findExpert: 'پیدا کردن استاد',
    ask: 'پرسش‌های دینی',
    home: 'خانه',
    experts: 'اساتید و مشاوران',
    services: 'خدمات',
    library: 'کتابخانه',
    events: 'رویدادها',
    about: 'دربارهٔ ما',
    login: 'ورود و عضویت',
    explore: 'کشف کنید',
    viewAll: 'مشاهدهٔ همه',
    demo: 'پیش‌نمایش طراحی · اطلاعات نمونه',
    demoDetail: 'این محیط برای بررسی طراحی است. اطلاعات نمایشی‌اند و عملیات واقعی انجام نمی‌شود.',
    close: 'بستن',
    menu: 'فهرست',
    dashboards: 'محیط‌های کاری',
    chooseRole: 'انتخاب محیط کاری',
    dashboard: 'نمای کلی',
    search: 'جست‌وجو',
    searchHint: 'چه چیزی در ذهن شماست؟',
    searchWork: 'جست‌وجو در این محیط…',
    searchExperts: 'نام یا تخصص استاد…',
    empty: 'نتیجه‌ای پیدا نشد',
    emptyHint: 'عبارت دیگری را امتحان کنید یا فیلترها را پاک کنید.',
    clear: 'پاک کردن فیلترها',
    all: 'همه',
    family: 'خانواده و روابط',
    faith: 'دین و زندگی',
    parenting: 'تربیت فرزند',
    growth: 'رشد فردی',
    online: 'گفت‌وگوی آنلاین',
    sampleExpert: 'پروفایل نمونه',
    profile: 'مشاهدهٔ پروفایل',
    specialties: 'یک قدم نزدیک‌تر به پاسخ',
    specialtiesIntro: 'موضوعی را انتخاب کنید که این روزها بیشتر به آن فکر می‌کنید.',
    expertsTitle: 'همراهانی برای شنیدن شما',
    expertsIntro: 'پیش‌نمایشی از شیوهٔ معرفی تخصص، رویکرد و زمان گفت‌وگو.',
    trust1: 'با احترام به حریم شما',
    trust2: 'فرصت انتخاب آگاهانه',
    trust3: 'همراهی به زبان شما',
    trustText: 'آرامش و اختیار شما، بخشی از هر گفت‌وگوست.',
    quote: 'گاهی، یک گفت‌وگوی خوب\nآغاز یک مسیر تازه است.',
    quoteSource: 'نگاه ویانور به همراهی',
    journey: 'همراهی، در سه قدم ساده',
    step1: 'موضوعتان را پیدا کنید',
    step1Text: 'از میان موضوع‌ها، مسیر نزدیک به نیازتان را انتخاب کنید.',
    step2: 'همراهتان را بشناسید',
    step2Text: 'تخصص و رویکرد استاد را با آرامش بررسی کنید.',
    step3: 'با آگاهی ادامه دهید',
    step3Text: 'در مراحل بعد، زمان مناسب را برای گفت‌وگو رزرو خواهید کرد.',
    reading: 'چند دقیقه برای خودتان',
    readMore: 'ادامهٔ مطلب',
    article1: 'شنیدن، اولین قدمِ یک گفت‌وگوی خوب',
    article2: 'چطور پرسش بهتری بپرسیم؟',
    article3: 'برای رشد، از قدم‌های کوچک شروع کنیم',
    minutes: 'دقیقه مطالعه',
    cta: 'لازم نیست همهٔ پاسخ‌ها را تنها پیدا کنید.',
    ctaText: 'موضوعتان را پیدا کنید و با مسیرهای همراهی ویانور آشنا شوید.',
    footerText: 'جایی برای گفت‌وگوهای محترمانه، پرسش‌های صادقانه و قدم‌های آگاهانه.',
    links: 'دسترسی سریع',
    help: 'راهنما و پشتیبانی',
    faq: 'پرسش‌های متداول',
    contact: 'ارتباط با ما',
    privacy: 'حریم خصوصی',
    terms: 'شرایط استفاده',
    copyright: 'ویانور · پیش‌نمایش رابط کاربری',
    greeting: 'سلام، به فضای خودتان خوش آمدید',
    sampleDate: 'چهارشنبه، ۱۵ مهر · روز نمونه',
    today: 'امروز',
    week: 'این هفته',
    month: 'این ماه',
    activity: 'روند فعالیت',
    activityHint: 'نمایش نمونهٔ فعالیت در بازهٔ انتخابی',
    recent: 'در یک نگاه',
    upcoming: 'برنامهٔ پیش رو',
    quick: 'دسترسی سریع',
    details: 'مشاهدهٔ جزئیات',
    pending: 'در انتظار',
    scheduled: 'برنامه‌ریزی‌شده',
    complete: 'تکمیل‌شده',
    review: 'نیازمند بررسی',
    status: 'وضعیت',
    title: 'عنوان',
    time: 'زمان نمونه',
    action: 'جزئیات',
    showAll: 'نمایش همهٔ موارد',
    notifications: 'اعلان‌ها',
    notificationText: 'محیط نمونهٔ شما آمادهٔ بررسی است.',
    noAction: 'این قابلیت در نسخهٔ عملیاتی فعال خواهد شد.',
    sampleNotice: 'جزئیات نمایشی؛ هیچ درخواست واقعی ثبت نمی‌شود.',
    continue: 'متوجه شدم',
    helpCard: 'همراه شما هستیم',
    helpCardText: 'راهنمای محیط کاری را مرور کنید.',
    viewGuide: 'مشاهدهٔ راهنما',
    settings: 'تنظیمات',
    backHome: 'بازگشت به خانه',
    saved: 'ذخیره شد',
    save: 'ذخیرهٔ نمونه',
    download: 'دریافت گزارش نمونه',
    calendar: 'تقویم',
    calendarHint: 'روز مورد نظر را برای مشاهدهٔ برنامهٔ نمونه انتخاب کنید.',
    selectedDay: 'برنامهٔ روز انتخاب‌شده',
    viewDashboard: 'ورود به پیش‌نمایش',
    roleIntro:
      'هر نقش، فضای متناسب با مسئولیت‌های خودش را دارد. این پیش‌نمایش‌ها به دادهٔ واقعی متصل نیستند.',
    faq1: 'آیا در این نسخه می‌توانم جلسه رزرو کنم؟',
    faq1Answer: 'این نسخه پیش‌نمایش طراحی است. رزرو و پرداخت واقعی در مراحل بعد فعال می‌شوند.',
    faq2: 'چگونه استاد مناسب را پیدا کنم؟',
    faq2Answer:
      'در فهرست اساتید، موضوع را انتخاب کنید و پروفایل‌ها را بررسی کنید. اطلاعات فعلی نمونه هستند.',
    faq3: 'آیا می‌توانم زبان محیط را تغییر دهم؟',
    faq3Answer:
      'بله؛ از انتخاب زبان در بالای صفحه استفاده کنید. همان صفحه به زبان دیگر نمایش داده می‌شود.',
    aboutText:
      'ویانور با یک ایده شکل می‌گیرد: دسترسی آسان‌تر به همراهی آگاهانه و محترمانه. در طراحی این فضا، شنیده‌شدن، انتخاب و حفظ حریم شخصی در مرکز توجه قرار دارند.',
    contactText:
      'راه‌های ارتباط رسمی در زمان راه‌اندازی خدمت اعلام می‌شوند. فعلاً می‌توانید راهنما و پرسش‌های متداول را مرور کنید.',
    policyText:
      'متن نهایی این سیاست پیش از راه‌اندازی خدمت منتشر خواهد شد. این صفحه صرفاً پیش‌نمایش چیدمان سند است و توافق حقوقی قابل پذیرش نیست.',
    authText:
      'ورود و ثبت‌نام در مرحلهٔ بعد فعال می‌شوند. اکنون می‌توانید بدون واردکردن اطلاعات شخصی، ظاهر محیط‌های کاری را ببینید.',
    articleText:
      'گفت‌وگو با توجه آغاز می‌شود. پیش از پاسخ‌دادن، کمی مکث کنیم، پرسش را روشن‌تر کنیم و برای شنیدن تجربهٔ دیگری جا باز کنیم. این متن کوتاه برای نمایش طراحی صفحهٔ محتوا نوشته شده است.',
    eventText: 'پیش‌نمایش رویداد آموزشی؛ زمان و سخنران نهایی پس از راه‌اندازی اعلام می‌شوند.',
    emptyLive: 'هنوز اطلاعات واقعی در این بخش وجود ندارد.',
    working: 'در حال آماده‌سازی',
    preview: 'نمونه',
    filters: 'فیلتر موضوع',
    navLabel: 'ناوبری اصلی',
    workspaceNav: 'ناوبری محیط کاری',
    weekdays: 'ش ی د س چ پ ج',
    balance: 'خلاصهٔ گزارش نمونه',
    wellbeing: 'کمی مکث، کمی آرامش',
    wellbeingText: 'برای تصمیم‌های بهتر، به خودتان فرصت بدهید.',
    overviewText: 'مهم‌ترین کارها و پیگیری‌ها، یک‌جا و در دسترس شما.',
    roleAction: 'بررسی برنامهٔ امروز',
    sectionIntro: 'فهرست نمونه برای بررسی چیدمان و تعامل این بخش.',
    welcomeName: 'همراه عزیز',
    sampleName: 'کاربر نمونه',
    expertBio:
      'این پروفایل برای نمایش طراحی ساخته شده و متعلق به فرد واقعی نیست. در نسخهٔ نهایی، تخصص‌ها، رویکرد و زمان‌های قابل رزرو در این قسمت نمایش داده می‌شوند.',
    approach: 'رویکرد و زمینهٔ همراهی',
    available: 'زمان‌های نمونهٔ گفت‌وگو',
    joinText:
      'در نسخهٔ عملیاتی، مسیر ثبت تخصص، بررسی مدارک و آغاز همکاری از این بخش در دسترس خواهد بود.',
    aboutService: 'دربارهٔ این خدمت',
    viewTopics: 'مشاهدهٔ موضوع‌ها',
  },
  en: {
    brand: 'Vianoor',
    tagline: 'A little light for life',
    language: 'فارسی',
    skip: 'Skip to main content',
    intro:
      'A thoughtful space to ask, be heard, and find a clearer way forward with caring experts.',
    eyebrow: 'A little understanding. A clearer path.',
    hero1: 'For every question,',
    hero2: 'a thoughtful companion.',
    findExpert: 'Find an expert',
    ask: 'Explore questions',
    home: 'Home',
    experts: 'Experts',
    services: 'Services',
    library: 'Library',
    events: 'Events',
    about: 'About',
    login: 'Sign in / Join',
    explore: 'Explore',
    viewAll: 'View all',
    demo: 'Design preview · Sample data',
    demoDetail:
      'This workspace previews the design. All records are samples; no real operations are performed.',
    close: 'Close',
    menu: 'Menu',
    dashboards: 'Workspaces',
    chooseRole: 'Choose a workspace',
    dashboard: 'Overview',
    search: 'Search',
    searchHint: 'What’s on your mind?',
    searchWork: 'Search this workspace…',
    searchExperts: 'Name or area of expertise…',
    empty: 'No results found',
    emptyHint: 'Try another phrase or clear your filters.',
    clear: 'Clear filters',
    all: 'All',
    family: 'Family & relationships',
    faith: 'Faith & everyday life',
    parenting: 'Parenting',
    growth: 'Personal growth',
    online: 'Online conversation',
    sampleExpert: 'Sample profile',
    profile: 'View profile',
    specialties: 'One step closer to clarity',
    specialtiesIntro: 'Start with what matters to you today.',
    expertsTitle: 'A thoughtful person on the other side',
    expertsIntro: 'Preview how expertise, approach, and availability come together.',
    trust1: 'Respect for your privacy',
    trust2: 'Space for an informed choice',
    trust3: 'Guidance in your language',
    trustText: 'Your comfort and choice belong in every conversation.',
    quote: 'Sometimes, a good conversation\nis the start of something new.',
    quoteSource: 'The spirit of Vianoor',
    journey: 'Three small steps to begin',
    step1: 'Find your topic',
    step1Text: 'Choose the topic closest to what you need.',
    step2: 'Meet your companion',
    step2Text: 'Take your time to explore an expert’s approach.',
    step3: 'Continue with clarity',
    step3Text: 'Booking a time for your conversation will follow in a later release.',
    reading: 'A few minutes for yourself',
    readMore: 'Read the story',
    article1: 'Listening is where a good conversation begins',
    article2: 'How do we ask a better question?',
    article3: 'Growth begins with small steps',
    minutes: 'min read',
    cta: 'You don’t have to find every answer alone.',
    ctaText: 'Explore your topic and discover the ways Vianoor can help.',
    footerText: 'A place for respectful conversations, honest questions, and thoughtful steps.',
    links: 'Quick links',
    help: 'Help & support',
    faq: 'FAQ',
    contact: 'Contact',
    privacy: 'Privacy',
    terms: 'Terms',
    copyright: 'Vianoor · Interface preview',
    greeting: 'Welcome to your space',
    sampleDate: 'Wednesday, 7 October · Sample day',
    today: 'Today',
    week: 'This week',
    month: 'This month',
    activity: 'Activity overview',
    activityHint: 'Sample activity for the selected period',
    recent: 'At a glance',
    upcoming: 'Coming up next',
    quick: 'Quick actions',
    details: 'View details',
    pending: 'Pending',
    scheduled: 'Scheduled',
    complete: 'Complete',
    review: 'Needs review',
    status: 'Status',
    title: 'Title',
    time: 'Sample time',
    action: 'Details',
    showAll: 'Show all records',
    notifications: 'Notifications',
    notificationText: 'Your sample workspace is ready to explore.',
    noAction: 'This action will be available in the operational release.',
    sampleNotice: 'Preview details; no real request is submitted.',
    continue: 'Got it',
    helpCard: 'We’re here to help',
    helpCardText: 'Find your way around your workspace.',
    viewGuide: 'Read the guide',
    settings: 'Settings',
    backHome: 'Back to home',
    saved: 'Saved',
    save: 'Save sample',
    download: 'Download sample report',
    calendar: 'Calendar',
    calendarHint: 'Select a day to see the sample schedule.',
    selectedDay: 'Selected day’s schedule',
    viewDashboard: 'Open preview',
    roleIntro:
      'Each role has a space built around its responsibilities. These previews are not connected to real data.',
    faq1: 'Can I book a session in this version?',
    faq1Answer: 'This is a design preview. Real booking and payment will be added in later stages.',
    faq2: 'How do I find a suitable expert?',
    faq2Answer:
      'Choose a topic in the expert directory and explore profiles. Current profiles are samples.',
    faq3: 'Can I change the interface language?',
    faq3Answer:
      'Yes. Use the language switch in the header to view the same page in the other language.',
    aboutText:
      'Vianoor begins with a simple idea: making thoughtful, respectful guidance more accessible. Listening, choice, and personal privacy shape this space.',
    contactText:
      'Official contact channels will be announced when the service launches. For now, explore the help center and frequently asked questions.',
    policyText:
      'The final policy will be published before the service launches. This page previews the document layout and is not a legal agreement to accept.',
    authText:
      'Sign-in and registration arrive in the next stage. You can explore the workspaces now without entering personal information.',
    articleText:
      'A conversation begins with attention. Before answering, we can pause, clarify the question, and make space for another person’s experience. This short passage illustrates the content-page design.',
    eventText:
      'An educational event preview. Final dates and speakers will be announced after launch.',
    emptyLive: 'There are no live records in this section yet.',
    working: 'Coming soon',
    preview: 'Sample',
    filters: 'Topic filter',
    navLabel: 'Main navigation',
    workspaceNav: 'Workspace navigation',
    weekdays: 'M T W T F S S',
    balance: 'Sample report summary',
    wellbeing: 'Pause. Breathe. Begin again.',
    wellbeingText: 'Give yourself a moment to make room for clarity.',
    overviewText: 'Your priorities and follow-ups, together in one thoughtful space.',
    roleAction: 'Explore today’s plan',
    sectionIntro: 'Sample records to explore this section’s layout and interactions.',
    welcomeName: 'Dear companion',
    sampleName: 'Sample user',
    expertBio:
      'This profile demonstrates the design and does not represent a real person. Expertise, approach, and bookable times will appear here in the final service.',
    approach: 'Approach & expertise',
    available: 'Sample conversation times',
    joinText:
      'In the operational release, this space will guide you through sharing your expertise, credential review, and joining the community.',
    aboutService: 'About this service',
    viewTopics: 'Explore topics',
  },
} as const;
