import { createDictionary } from './localization-runtime';
export const discoveryCopy = createDictionary('discoveryCopy', {
  en: {
    title: 'Find an expert',
    discoveryEyebrow: 'Verified experts · real availability',
    discoveryIntro:
      'Browse experts first, then narrow the list by language, specialty, topic, price, live presence, availability and rating.',
    filters: 'Filters',
    clearFilters: 'Clear',
    specialty: 'Specialty',
    topic: 'Topic',
    maxPrice: 'Maximum price',
    anyPrice: 'Any price',
    minimumRating: 'Minimum rating',
    anyRating: 'Any rating',
    onlineNow: 'Online now',
    availableToday: 'Available today',
    applyFilters: 'Apply filters',
    expertsFound: 'experts',
    gridFirst: 'Verified public profiles',
    sort: 'Sort',
    recommended: 'Recommended',
    earliest: 'Earliest appointment',
    rating: 'Rating',
    price: 'Price',
    online: 'Online',
    away: 'Away',
    offline: 'Offline',
    noRatings: 'No ratings yet',
    from: 'From',
    priceUnavailable: 'Price on profile',
    noAvailability: 'No open time in the next 7 days',
    viewProfile: 'View profile',
    viewTimes: 'View times',
    emptyHint: 'Try removing one or more filters.',
    intent: 'What help do you need?',
    spoken: 'Consultation language',
    language: 'Language',
    any: 'Any language',
    search: 'Search',
    guided: 'Find a time',
    when: 'Your local date and time',
    timezone: 'Time zone',
    next: 'Next',
    previous: 'Previous',
    empty: 'No matching experts found.',
    busy: 'Loading…',
    error: 'The request could not be completed. Please try again.',
    admin: 'Languages and translations',
    languages: 'Languages',
    translations: 'Page translations',
    synonyms: 'Search dictionary',
    specialties: 'Specialty translations',
    coverage: 'Published translations',
    source: 'English source',
    value: 'Translation',
    missing: 'Only missing translations',
    filter: 'Filter',
    save: 'Save draft',
    saved: 'Saved',
    review: 'Mark as reviewed',
    approve: 'Approve and publish',
    add: 'Add',
    remove: 'Remove',
    active: 'Active',
    name: 'English name',
    native: 'Native name',
    direction: 'Direction',
    ai: 'AI capability',
    speech: 'Speech capability',
    translation: 'Translation capability',
    code: 'Language code',
    edit: 'Edit',
    close: 'Close',
    status: 'Status',
    rebuild: 'Refresh search index',
    queue: 'Queue translation',
    waiting: 'Waiting for a translation provider',
    sourceLanguage: 'Original content language',
    dynamic: 'Profile and service translations',
    unknown: 'Unspecified',
    choose: 'Choose an item',
    profile: 'Profile',
    service: 'Service',
    published: 'Published',
    pending: 'Not published',
    fallback: 'Missing translations use English.',
    timeNote: 'Availability is checked now. Your time is reserved only after booking.',
    book: 'Book this session',
    dictionarySource: 'Source phrase',
    dictionaryTarget: 'Equivalent phrase',
    sourceCode: 'Source language',
    targetCode: 'Target language',
    key: 'Key',
    module: 'Module',
    createKey: 'Add English text',
    all: 'All',
    fields: {
      display_name: 'Display name',
      title: 'Title',
      short_bio: 'Short introduction',
      biography: 'Biography',
      experience: 'Experience',
      education: 'Education',
      city: 'City',
      country: 'Country',
      seo_title: 'Search title',
      seo_description: 'Search description',
      summary: 'Summary',
      description: 'Description',
      terms: 'Terms',
    },
  },
  fa: {
    title: 'پیدا کردن استاد',
    discoveryEyebrow: 'اساتید تأییدشده · زمان‌های واقعی',
    discoveryIntro:
      'ابتدا استادها را ببینید و سپس با زبان، تخصص، موضوع، قیمت، وضعیت آنلاین، زمان آزاد و امتیاز فهرست را محدود کنید.',
    filters: 'فیلترها',
    clearFilters: 'پاک کردن',
    specialty: 'تخصص',
    topic: 'موضوع',
    maxPrice: 'حداکثر قیمت',
    anyPrice: 'بدون محدودیت',
    minimumRating: 'حداقل امتیاز',
    anyRating: 'همه امتیازها',
    onlineNow: 'الان آنلاین',
    availableToday: 'امروز وقت آزاد دارد',
    applyFilters: 'اعمال فیلترها',
    expertsFound: 'استاد',
    gridFirst: 'پروفایل‌های عمومی تأییدشده',
    sort: 'مرتب‌سازی',
    recommended: 'پیشنهادی',
    earliest: 'نزدیک‌ترین وقت',
    rating: 'بالاترین امتیاز',
    price: 'کمترین قیمت',
    online: 'آنلاین',
    away: 'دور از سیستم',
    offline: 'آفلاین',
    noRatings: 'هنوز امتیازی ثبت نشده',
    from: 'از',
    priceUnavailable: 'قیمت در پروفایل',
    noAvailability: 'در ۷ روز آینده وقت آزادی ثبت نشده',
    viewProfile: 'مشاهده پروفایل',
    viewTimes: 'مشاهده زمان‌ها',
    emptyHint: 'یک یا چند فیلتر را حذف کنید.',
    intent: 'در چه زمینه‌ای کمک می‌خواهید؟',
    spoken: 'زبان جلسه',
    language: 'زبان',
    any: 'همه زبان‌ها',
    search: 'جستجو',
    guided: 'پیدا کردن زمان',
    when: 'تاریخ و ساعت به وقت شما',
    timezone: 'منطقه زمانی',
    next: 'بعدی',
    previous: 'قبلی',
    empty: 'استادی با این شرایط پیدا نشد.',
    busy: 'در حال دریافت…',
    error: 'درخواست انجام نشد؛ دوباره تلاش کنید.',
    admin: 'زبان‌ها و ترجمه‌ها',
    languages: 'زبان‌ها',
    translations: 'ترجمه صفحات',
    synonyms: 'واژه‌نامه جستجو',
    specialties: 'ترجمه تخصص‌ها',
    coverage: 'ترجمه‌های منتشرشده',
    source: 'متن اصلی انگلیسی',
    value: 'ترجمه',
    missing: 'فقط ترجمه‌های ناقص',
    filter: 'فیلتر',
    save: 'ذخیره پیش‌نویس',
    saved: 'ذخیره شد',
    review: 'ثبت بازبینی',
    approve: 'تأیید و انتشار',
    add: 'افزودن',
    remove: 'حذف',
    active: 'فعال',
    name: 'نام انگلیسی',
    native: 'نام بومی',
    direction: 'جهت نوشتار',
    ai: 'قابلیت هوش مصنوعی',
    speech: 'قابلیت گفتار',
    translation: 'قابلیت ترجمه',
    code: 'کد زبان',
    edit: 'ویرایش',
    close: 'بستن',
    status: 'وضعیت',
    rebuild: 'به‌روزرسانی نمایه جستجو',
    queue: 'افزودن به صف ترجمه',
    waiting: 'در انتظار اتصال سرویس ترجمه',
    sourceLanguage: 'زبان متن اصلی',
    dynamic: 'ترجمه پروفایل و خدمات',
    unknown: 'مشخص نشده',
    choose: 'انتخاب کنید',
    profile: 'پروفایل',
    service: 'خدمت',
    published: 'منتشرشده',
    pending: 'منتشر نشده',
    fallback: 'ترجمه‌های ناقص به انگلیسی نمایش داده می‌شوند.',
    timeNote: 'ظرفیت همین حالا بررسی می‌شود. زمان فقط پس از انجام رزرو برای شما نگه داشته می‌شود.',
    book: 'رزرو این جلسه',
    dictionarySource: 'عبارت مبدأ',
    dictionaryTarget: 'عبارت هم‌معنی',
    sourceCode: 'زبان مبدأ',
    targetCode: 'زبان مقصد',
    key: 'کلید',
    module: 'بخش',
    createKey: 'افزودن متن انگلیسی',
    all: 'همه',
    fields: {
      display_name: 'نام نمایشی',
      title: 'عنوان',
      short_bio: 'معرفی کوتاه',
      biography: 'زندگی‌نامه',
      experience: 'سوابق',
      education: 'تحصیلات',
      city: 'شهر',
      country: 'کشور',
      seo_title: 'عنوان جستجو',
      seo_description: 'توضیح جستجو',
      summary: 'خلاصه',
      description: 'توضیح',
      terms: 'شرایط',
    },
  },
});
