export const expertsPublicCopy = {
  fa: {
    title: 'اساتید تأییدشده',
    empty: 'هنوز پروفایل عمومی منتشر نشده است.',
    unavailable: 'فهرست اساتید در دسترس نیست.',
    home: 'خانه',
    back: 'فهرست اساتید',
    verified: 'استاد تأییدشده',
    education: 'تحصیلات',
    experience: 'سوابق',
    specialties: 'تخصص‌ها',
    languages: 'زبان‌ها',
    documents: 'مدارک تأییدشده',
    services: 'خدمات و تعرفه‌ها',
    note: 'رزرو و پرداخت در مراحل بعد فعال می‌شوند.',
    minutes: 'دقیقه',
  },
  en: {
    title: 'Verified experts',
    empty: 'No public profiles have been published yet.',
    unavailable: 'Expert directory is unavailable.',
    home: 'Home',
    back: 'Expert directory',
    verified: 'Verified expert',
    education: 'Education',
    experience: 'Experience',
    specialties: 'Specialties',
    languages: 'Languages',
    documents: 'Verified credentials',
    services: 'Services and pricing',
    note: 'Booking and payment will be added in a later stage.',
    minutes: 'minutes',
  },
};
