import { createDictionary } from './localization-runtime';
export const financeCopy = createDictionary('financeCopy', {
  en: {
    id: 'ID',
    booking_id: 'Booking',
    payment_id: 'Payment',
    account_id: 'Account',
    kind: 'Balance type',
    description: 'Operation',
    created_at: 'Date',
    target: 'Destination',
    provider_reference: 'Provider reference',
    basis_points: 'Commission (basis points)',
    active: 'Active',
    connection_status: 'Connection',
    enabled: 'Enabled',
    tax: 'Tax',
    tax_bps: 'Included tax (basis points; 0 disables tax)',
    risk: 'Risk signals',
    riskSettings: 'Fraud controls',
    review_spikes: 'Review unusual amount increases',
    ipinfo_token: 'IPinfo access token (optional)',
    ipinfo_configured: 'IP country lookup configured',
    riskHint:
      'Optional IPinfo country lookup sends the payer IP to IPinfo. Without a token, the country is recorded as unknown. Credentials remain encrypted.',
    RISK_REVIEW: 'Awaiting financial review',
    approveRisk: 'Approve after risk review',
    AVAILABLE: 'Available',
    LOCKED: 'Locked',
    CONNECTED: 'Connected',
    NOT_TESTED: 'Not checked',
    RESTRICTED: 'Restricted',
    trial_balance: 'Trial balance',
    lines: 'Journal entries',
    valid_until: 'Valid until',
    title: 'Payments and wallet',
    admin: 'Finance management',
    wallet: 'Wallet',
    gateways: 'Payment gateways',
    payments: 'Payments',
    ledger: 'Accounting ledger',
    refunds: 'Refund requests',
    payouts: 'Withdrawals',
    disputes: 'Disputes',
    reports: 'Financial reports',
    settings: 'Fees and limits',
    rates: 'Exchange rates',
    reconciliation: 'Reconciliation',
    refresh: 'Refresh',
    save: 'Save',
    test: 'Check connection',
    enable: 'Enable',
    disable: 'Disable',
    provider: 'Payment method',
    mode: 'Mode',
    testMode: 'Test',
    liveMode: 'Live',
    currencies: 'Currencies (comma separated)',
    countries: 'Countries (ISO codes, optional)',
    secret_key: 'Stripe secret key',
    webhook_secret: 'Stripe webhook signing secret',
    client_id: 'PayPal client ID',
    client_secret: 'PayPal client secret',
    webhook_id: 'PayPal webhook ID',
    api_key: 'NOWPayments API key',
    ipn_secret: 'NOWPayments IPN secret',
    payout_email: 'NOWPayments payout login email (optional)',
    payout_password: 'NOWPayments payout login password (optional)',
    keysHint:
      'Saved keys are encrypted and never displayed. Leave a field empty to keep its saved value. Saving creates a new configuration; check the connection and enable it.',
    webhook: 'Webhook address',
    webhookHint:
      'Copy this address into the provider dashboard. Card, Apple Pay and Google Pay are handled by Stripe’s secure checkout; wallet buttons appear on supported devices and merchant accounts.',
    configured: 'Configured',
    notConfigured: 'Not configured',
    disabled: 'Unavailable until the administrator completes setup',
    amount: 'Amount',
    currency: 'Currency',
    network: 'Crypto network',
    pay: 'Continue to payment',
    topup: 'Add balance',
    booking: 'Booking',
    available: 'Available',
    pending: 'Pending',
    locked: 'Locked',
    history: 'Transactions',
    empty: 'No records yet.',
    status: 'Status',
    reference: 'Reference',
    created: 'Date',
    fee: 'Platform fee',
    balance: 'Balance',
    debit: 'Debit',
    credit: 'Credit',
    checkout: 'Open secure checkout',
    address: 'Payment address',
    cryptoAmount: 'Exact crypto amount',
    cryptoHint:
      'Send only the displayed currency on the selected network. An underpayment does not confirm the booking.',
    remaining: 'Payment status',
    review: 'Check payment status',
    refund: 'Request refund',
    refundWallet: 'Refund to wallet',
    refundOriginal: 'Refund to original method',
    refundHint:
      'Crypto refunds are credited to the wallet; conversion and withdrawal use the selected network and an approved payout.',
    approve: 'Approve',
    reject: 'Reject',
    process: 'Process',
    complete: 'Record completed bank transfer',
    details: 'View protected details',
    verify: 'Verify crypto withdrawal',
    verificationCode: 'One-time provider verification code',
    destination: 'Payout destination',
    addDestination: 'Add destination',
    method: 'Method',
    bank: 'Bank',
    account: 'Account / IBAN',
    holder: 'Account holder',
    country: 'Country (ISO)',
    email: 'PayPal email',
    withdraw: 'Request withdrawal',
    withdrawHint:
      'Funds remain locked until payment succeeds or is definitively rejected. A bank transfer is completed by an administrator using the bank receipt.',
    newDispute: 'Open a dispute',
    reason: 'Reason',
    message: 'Message',
    send: 'Send message',
    attachments: 'Evidence file IDs (optional)',
    resolveRefund: 'Resolve with wallet refund',
    resolveRelease: 'Resolve and release',
    base: 'From currency',
    quote: 'To currency',
    numerator: 'Rate numerator',
    denominator: 'Rate denominator',
    validUntil: 'Valid until (UTC)',
    source: 'Rate source',
    quoteRate: 'Get conversion quote',
    exchange: 'Confirm conversion',
    commission_bps: 'Default commission (basis points: 2000 = 20%)',
    release_hours: 'Hours after session before funds become available',
    max_hourly_attempts: 'Maximum payment attempts per hour',
    max_topup_minor: 'Maximum top-up in minor units',
    expert_id: 'Expert account ID (optional)',
    specialty_id: 'Specialty ID (optional)',
    service_kind: 'Service type (optional)',
    priority: 'Priority',
    newRule: 'Add commission rule',
    period: 'Report period',
    day: 'Daily',
    month: 'Monthly',
    year: 'Yearly',
    gross: 'Gross payments',
    commission: 'Commission',
    net_revenue: 'Released revenue',
    count: 'Count',
    close: 'Close',
    success: 'Saved successfully.',
    error: 'The operation could not be completed',
    bookings: 'My bookings',
    paymentNotice: 'Free sessions confirm immediately. Paid sessions require a verified payment.',
    BOOKING_PENDING_PAYMENT: 'Awaiting payment',
    SUCCESS: 'Paid',
    PENDING: 'Pending',
    CREATED: 'Created',
    AUTHORIZED: 'Authorized',
    FAILED: 'Failed',
    CANCELLED: 'Cancelled',
    EXPIRED: 'Expired',
    PARTIAL: 'Partially paid',
    REFUNDED: 'Refunded',
    REQUESTED: 'Requested',
    APPROVED: 'Approved',
    PROCESSING: 'Processing',
    COMPLETED: 'Completed',
    REJECTED: 'Rejected',
    OPEN: 'Open',
    RESOLVED: 'Resolved',
    APPLIED: 'Applied',
    CREDITED_LATE: 'Hold expired; amount credited to wallet',
    CREATE_UNCERTAIN: 'Creation requires reconciliation',
    SUBMITTED: 'Awaiting provider confirmation',
    NO_SHOW: 'Expert did not attend',
    QUALITY: 'Service quality',
    REFUND: 'Refund request',
    OTHER: 'Other',
    PAYMENT_ERROR: 'Payment error',
    EXPERT_CANCELLED: 'Expert cancelled',
    INSUFFICIENT_BALANCE: 'Insufficient available balance.',
    GATEWAY_NOT_CONFIGURED: 'This payment method is not configured yet.',
    RISK_LIMIT: 'The payment limit has been reached.',
    PAYMENT_REQUIRED: 'Payment is required to confirm this booking.',
    HOLD_EXPIRED: 'The booking hold has expired.',
    BOOKING_ALREADY_PAID: 'A payment already exists for this booking.',
    PROVIDER_UNCERTAIN:
      'The provider response is uncertain. Check this payment again; do not create another.',
    PROVIDER_CREDENTIALS_REJECTED: 'The provider rejected these credentials.',
    RATE_UNAVAILABLE: 'No active exchange rate is configured.',
    QUOTE_EXPIRED: 'The conversion quote expired; request a new quote.',
    CRYPTO_REFUND_REQUIRES_PAYOUT: 'Choose wallet refund, then request a crypto withdrawal.',
    STRIPE: 'Visa / Mastercard · Apple Pay / Google Pay',
    PAYPAL: 'PayPal',
    NOWPAYMENTS: 'Crypto',
    WALLET: 'Wallet',
  },
  fa: {
    id: 'شناسه',
    booking_id: 'رزرو',
    payment_id: 'پرداخت',
    account_id: 'حساب',
    kind: 'نوع موجودی',
    description: 'عملیات',
    created_at: 'تاریخ',
    target: 'مقصد',
    provider_reference: 'پیگیری ارائه‌دهنده',
    basis_points: 'کارمزد (واحد پایه)',
    active: 'فعال',
    connection_status: 'اتصال',
    enabled: 'فعال',
    tax: 'مالیات',
    tax_bps: 'مالیاتِ داخل مبلغ (واحد پایه؛ صفر یعنی بدون مالیات)',
    risk: 'نشانه‌های ریسک',
    riskSettings: 'کنترل تقلب',
    review_spikes: 'بررسی افزایش غیرمعمول مبلغ',
    ipinfo_token: 'توکن IPinfo (اختیاری)',
    ipinfo_configured: 'تشخیص کشور IP تنظیم شده',
    riskHint:
      'تشخیص اختیاری کشور با IPinfo، IP پرداخت‌کننده را برای این سرویس می‌فرستد. بدون توکن، کشور نامشخص ثبت می‌شود. کلید رمزنگاری خواهد شد.',
    RISK_REVIEW: 'در انتظار بررسی مالی',
    approveRisk: 'تأیید پس از بررسی ریسک',
    AVAILABLE: 'قابل مصرف',
    LOCKED: 'قفل‌شده',
    CONNECTED: 'متصل',
    NOT_TESTED: 'بررسی نشده',
    RESTRICTED: 'محدودشده',
    trial_balance: 'تراز آزمایشی',
    lines: 'ردیف‌های سند',
    valid_until: 'اعتبار تا',
    title: 'پرداخت و کیف پول',
    admin: 'مدیریت مالی',
    wallet: 'کیف پول',
    gateways: 'درگاه‌های پرداخت',
    payments: 'پرداخت‌ها',
    ledger: 'دفترکل حسابداری',
    refunds: 'درخواست‌های بازپرداخت',
    payouts: 'برداشت‌ها',
    disputes: 'اختلافات',
    reports: 'گزارش مالی',
    settings: 'کارمزد و محدودیت‌ها',
    rates: 'نرخ تبدیل ارز',
    reconciliation: 'تطبیق تراکنش‌ها',
    refresh: 'به‌روزرسانی',
    save: 'ذخیره',
    test: 'بررسی اتصال',
    enable: 'فعال‌سازی',
    disable: 'غیرفعال‌سازی',
    provider: 'روش پرداخت',
    mode: 'حالت',
    testMode: 'آزمایشی',
    liveMode: 'واقعی',
    currencies: 'ارزها (با کامای انگلیسی)',
    countries: 'کشورها (کد ISO، اختیاری)',
    secret_key: 'کلید محرمانه Stripe',
    webhook_secret: 'کلید امضای وب‌هوک Stripe',
    client_id: 'شناسهٔ کلاینت PayPal',
    client_secret: 'کلید محرمانه PayPal',
    webhook_id: 'شناسهٔ وب‌هوک PayPal',
    api_key: 'کلید API رمزارز NOWPayments',
    ipn_secret: 'کلید امضای IPN رمزارز',
    payout_email: 'ایمیل ورود برداشت NOWPayments (اختیاری)',
    payout_password: 'رمز ورود برداشت NOWPayments (اختیاری)',
    keysHint:
      'کلیدها رمزنگاری می‌شوند و دوباره نمایش داده نمی‌شوند. فیلد خالی، مقدار ذخیره‌شده را حفظ می‌کند. پس از ذخیره، اتصال را بررسی و درگاه را فعال کنید.',
    webhook: 'نشانی وب‌هوک',
    webhookHint:
      'این نشانی را در پنل ارائه‌دهنده قرار دهید. کارت، Apple Pay و Google Pay در صفحهٔ امن Stripe پردازش می‌شوند؛ دکمه‌های کیف پول بر اساس دستگاه و حساب پذیرنده نمایش داده می‌شوند.',
    configured: 'تنظیم‌شده',
    notConfigured: 'تنظیم نشده',
    disabled: 'پس از تکمیل تنظیمات توسط مدیر فعال می‌شود',
    amount: 'مبلغ',
    currency: 'ارز',
    network: 'شبکهٔ رمزارز',
    pay: 'ادامهٔ پرداخت',
    topup: 'شارژ کیف پول',
    booking: 'رزرو',
    available: 'قابل مصرف',
    pending: 'در انتظار',
    locked: 'قفل‌شده',
    history: 'گردش حساب',
    empty: 'هنوز رکوردی ثبت نشده است.',
    status: 'وضعیت',
    reference: 'شمارهٔ پیگیری',
    created: 'تاریخ',
    fee: 'سهم پلتفرم',
    balance: 'مانده',
    debit: 'بدهکار',
    credit: 'بستانکار',
    checkout: 'ورود به صفحهٔ امن پرداخت',
    address: 'آدرس پرداخت',
    cryptoAmount: 'مقدار دقیق رمزارز',
    cryptoHint:
      'فقط ارز نمایش‌داده‌شده را در شبکهٔ انتخاب‌شده ارسال کنید. پرداخت ناقص، رزرو را تأیید نمی‌کند.',
    remaining: 'وضعیت پرداخت',
    review: 'بررسی وضعیت پرداخت',
    refund: 'درخواست بازپرداخت',
    refundWallet: 'بازپرداخت به کیف پول',
    refundOriginal: 'بازپرداخت به روش اصلی',
    refundHint:
      'بازپرداخت رمزارز به کیف پول واریز می‌شود؛ تبدیل و برداشت با شبکهٔ انتخابی و تأیید درخواست انجام می‌شود.',
    approve: 'تأیید',
    reject: 'رد درخواست',
    process: 'پردازش',
    complete: 'ثبت انتقال بانکی انجام‌شده',
    details: 'مشاهدهٔ اطلاعات محافظت‌شده',
    verify: 'تأیید برداشت رمزارز',
    verificationCode: 'کد یک‌بارمصرف ارائه‌دهنده',
    destination: 'مقصد برداشت',
    addDestination: 'افزودن مقصد',
    method: 'روش',
    bank: 'بانک',
    account: 'شماره حساب / شبا',
    holder: 'صاحب حساب',
    country: 'کشور (کد ISO)',
    email: 'ایمیل PayPal',
    withdraw: 'درخواست برداشت',
    withdrawHint:
      'مبلغ تا موفقیت پرداخت یا رد قطعی قفل می‌ماند. انتقال بانکی با رسید بانک توسط مدیر تکمیل می‌شود.',
    newDispute: 'ثبت اختلاف',
    reason: 'دلیل',
    message: 'پیام',
    send: 'ارسال پیام',
    attachments: 'شناسهٔ فایل مدارک (اختیاری)',
    resolveRefund: 'حل اختلاف با بازپرداخت',
    resolveRelease: 'حل اختلاف و آزادسازی',
    base: 'از ارز',
    quote: 'به ارز',
    numerator: 'صورت نرخ',
    denominator: 'مخرج نرخ',
    validUntil: 'اعتبار تا (UTC)',
    source: 'منبع نرخ',
    quoteRate: 'دریافت نرخ تبدیل',
    exchange: 'تأیید تبدیل',
    commission_bps: 'کارمزد پیش‌فرض (۲۰۰۰ یعنی ۲۰٪)',
    release_hours: 'ساعت انتظار پس از جلسه برای آزادسازی',
    max_hourly_attempts: 'حداکثر تلاش پرداخت در ساعت',
    max_topup_minor: 'حداکثر شارژ برحسب کوچک‌ترین واحد ارز',
    expert_id: 'شناسهٔ حساب استاد (اختیاری)',
    specialty_id: 'شناسهٔ تخصص (اختیاری)',
    service_kind: 'نوع خدمت (اختیاری)',
    priority: 'اولویت',
    newRule: 'افزودن قانون کارمزد',
    period: 'دورهٔ گزارش',
    day: 'روزانه',
    month: 'ماهانه',
    year: 'سالانه',
    gross: 'جمع پرداخت‌ها',
    commission: 'کارمزد',
    net_revenue: 'درآمد آزادشده',
    count: 'تعداد',
    close: 'بستن',
    success: 'با موفقیت ذخیره شد.',
    error: 'عملیات انجام نشد',
    bookings: 'رزروهای من',
    paymentNotice: 'جلسات رایگان مستقیم تأیید می‌شوند؛ جلسات پولی به پرداخت معتبر نیاز دارند.',
    BOOKING_PENDING_PAYMENT: 'در انتظار پرداخت',
    SUCCESS: 'پرداخت‌شده',
    PENDING: 'در انتظار',
    CREATED: 'ایجادشده',
    AUTHORIZED: 'مجوز برداشت صادر شده',
    FAILED: 'ناموفق',
    CANCELLED: 'لغوشده',
    EXPIRED: 'منقضی‌شده',
    PARTIAL: 'پرداخت ناقص',
    REFUNDED: 'بازپرداخت‌شده',
    REQUESTED: 'درخواست‌شده',
    APPROVED: 'تأییدشده',
    PROCESSING: 'در حال پردازش',
    COMPLETED: 'تکمیل‌شده',
    REJECTED: 'ردشده',
    OPEN: 'باز',
    RESOLVED: 'حل‌شده',
    APPLIED: 'اعمال‌شده',
    CREDITED_LATE: 'مهلت رزرو تمام شده؛ مبلغ به کیف پول برگشت',
    CREATE_UNCERTAIN: 'ایجاد پرداخت نیازمند تطبیق است',
    SUBMITTED: 'در انتظار پاسخ ارائه‌دهنده',
    NO_SHOW: 'عدم حضور استاد',
    QUALITY: 'کیفیت خدمت',
    REFUND: 'درخواست بازگشت وجه',
    OTHER: 'سایر',
    PAYMENT_ERROR: 'خطای پرداخت',
    EXPERT_CANCELLED: 'لغو توسط استاد',
    INSUFFICIENT_BALANCE: 'موجودی قابل مصرف کافی نیست.',
    GATEWAY_NOT_CONFIGURED: 'این روش پرداخت هنوز تنظیم نشده است.',
    RISK_LIMIT: 'محدودیت پرداخت اعمال شده است.',
    PAYMENT_REQUIRED: 'برای تأیید این رزرو پرداخت لازم است.',
    HOLD_EXPIRED: 'مهلت نگهداری رزرو تمام شده است.',
    BOOKING_ALREADY_PAID: 'برای این رزرو پرداخت ثبت شده است.',
    PROVIDER_UNCERTAIN:
      'پاسخ درگاه قطعی نیست. همین پرداخت را دوباره بررسی کنید؛ پرداخت دیگری نسازید.',
    PROVIDER_CREDENTIALS_REJECTED: 'ارائه‌دهنده کلیدهای اتصال را نپذیرفت.',
    RATE_UNAVAILABLE: 'نرخ تبدیل فعالی تنظیم نشده است.',
    QUOTE_EXPIRED: 'اعتبار نرخ تمام شده؛ دوباره نرخ بگیرید.',
    CRYPTO_REFUND_REQUIRES_PAYOUT:
      'بازپرداخت به کیف پول را انتخاب و سپس برداشت رمزارز درخواست کنید.',
    STRIPE: 'ویزا / مسترکارت · Apple Pay / Google Pay',
    PAYPAL: 'پی‌پال',
    NOWPAYMENTS: 'رمزارز',
    WALLET: 'کیف پول',
  },
});
