import { createDictionary } from './localization-runtime';
export const schedulingCopy = createDictionary('schedulingCopy', {
  fa: {
    book: 'رزرو جلسه',
    calendar: 'تقویم کاری',
    bookings: 'رزروها و تقویم من',
    expertBookings: 'رزروهای استاد',
    adminBookings: 'مدیریت رزروها',
    holidays: 'تعطیلی‌ها و تنظیمات تقویم',
    timezone: 'منطقهٔ زمانی',
    saveTimezone: 'ذخیره منطقهٔ زمانی من',
    weekly: 'ساعات کاری هفتگی',
    breaks: 'زمان‌های استراحت',
    day: 'روز هفته',
    start: 'شروع',
    end: 'پایان',
    add: 'افزودن بازه',
    remove: 'حذف',
    save: 'ذخیره',
    refresh: 'به‌روزرسانی',
    before: 'فاصلهٔ پیش از جلسه (دقیقه)',
    after: 'فاصلهٔ پس از جلسه (دقیقه)',
    notice: 'حداقل فاصله تا رزرو (دقیقه)',
    horizon: 'حداکثر بازهٔ رزرو (روز)',
    cutoff: 'مهلت لغو یا تغییر زمان (ساعت پیش از جلسه)',
    exceptions: 'استثناهای تقویم',
    available: 'زمان کاری اضافه',
    unavailable: 'زمان مسدود',
    title: 'عنوان',
    kind: 'نوع',
    localStart: 'شروع محلی (تاریخ میلادی)',
    localEnd: 'پایان محلی (تاریخ میلادی)',
    disambiguation: 'ساعت تکراری هنگام تغییر ساعت تابستانی',
    reject: 'در صورت ابهام ثبت نشود',
    earlier: 'بار اول ساعت تکراری',
    later: 'بار دوم ساعت تکراری',
    expert: 'استاد',
    service: 'خدمت',
    select: 'انتخاب کنید',
    date: 'روز مورد نظر (تاریخ میلادی)',
    find: 'نمایش زمان‌های آزاد',
    slots: 'زمان‌های آزاد',
    hold: 'نگهداری موقت زمان',
    confirm: 'تأیید رزرو رایگان',
    cancel: 'لغو رزرو',
    reschedule: 'تغییر زمان',
    complete: 'ثبت پایان جلسه',
    free: 'در این مرحله فقط خدمات رایگان قابل رزرو هستند؛ پرداختی دریافت نمی‌شود.',
    expires: 'مهلت تأیید',
    remaining: 'ثانیه باقی مانده',
    empty: 'موردی یافت نشد.',
    loading: 'در حال بارگذاری…',
    saved: 'ذخیره شد.',
    error: 'عملیات انجام نشد؛ اطلاعات را بررسی و دوباره تلاش کنید.',
    conflict: 'این زمان را شخص دیگری گرفته است. زمان دیگری انتخاب کنید.',
    expired: 'مهلت نگهداری زمان پایان یافته است.',
    cutoffError: 'مهلت مجاز لغو یا تغییر زمان گذشته است.',
    ambiguous:
      'این ساعت وجود ندارد یا دو بار تکرار می‌شود؛ ساعت یا گزینهٔ رفع ابهام را تغییر دهید.',
    serviceUnavailable: 'این خدمت در حال حاضر قابل رزرو نیست.',
    policy: 'لغو و تغییر زمان توسط مراجع تا این تعداد ساعت پیش از شروع مجاز است:',
    noPenalty: 'در مرحلهٔ ۹ جریمه و بازپرداخت مالی نداریم.',
    status: 'وضعیت',
    period: 'بازهٔ نمایش',
    all: 'همه',
    future: 'آینده',
    past: 'گذشته',
    cancelled: 'لغوشده و منقضی',
    notifications: 'اعلان‌های رزرو',
    read: 'خوانده شد',
    searchTime: 'جستجوی استاد براساس زمان',
    searchAt: 'زمان مورد نظر شما (تاریخ میلادی)',
    search: 'جستجو',
    annual: 'هر سال تکرار شود',
    calendarType: 'تقویم تاریخ تعطیلی',
    gregorian: 'میلادی',
    persian: 'هجری شمسی',
    startDate: 'تاریخ شروع (YYYY-MM-DD)',
    endDate: 'تاریخ پایان، شامل این روز (YYYY-MM-DD)',
    holdSeconds: 'مهلت نگهداری ظرفیت (ثانیه)',
    calendarNote:
      'ساعت‌های هفتگی براساس منطقهٔ زمانی استاد هستند؛ استثناها به لحظهٔ دقیق UTC تبدیل می‌شوند. تغییر تقویم رزروهای قبلی را لغو نمی‌کند.',
    moveNote: 'تا قطعی‌شدن زمان جدید، رزرو قبلی محفوظ می‌ماند.',
    back: 'بازگشت',
    next: 'صفحهٔ بعد',
    previous: 'صفحهٔ قبل',
    utcOffset: 'زمان‌ها با منطقهٔ زمانی انتخابی نمایش داده می‌شوند.',
    days: ['دوشنبه', 'سه‌شنبه', 'چهارشنبه', 'پنجشنبه', 'جمعه', 'شنبه', 'یکشنبه'],
    states: {
      REQUESTED: 'درخواست‌شده',
      HELD: 'موقتاً نگه داشته‌شده',
      CONFIRMED: 'تأییدشده',
      COMPLETED: 'پایان‌یافته',
      CANCELLED: 'لغوشده',
      EXPIRED: 'منقضی',
      RESCHEDULE_REQUESTED: 'درخواست تغییر زمان',
      RESCHEDULED: 'زمان تغییرکرده',
      RESCHEDULE_REJECTED: 'تغییر زمان ناموفق',
      REMINDER: 'یادآوری جلسه',
    },
    pending: 'در حال نهایی‌سازی؛ دوباره به‌روزرسانی کنید.',
  },
  en: {
    book: 'Book a session',
    calendar: 'Working calendar',
    bookings: 'My bookings and calendar',
    expertBookings: 'Expert bookings',
    adminBookings: 'Booking management',
    holidays: 'Holidays and calendar settings',
    timezone: 'Time zone',
    saveTimezone: 'Save my time zone',
    weekly: 'Weekly working hours',
    breaks: 'Breaks',
    day: 'Weekday',
    start: 'Start',
    end: 'End',
    add: 'Add interval',
    remove: 'Remove',
    save: 'Save',
    refresh: 'Refresh',
    before: 'Buffer before (minutes)',
    after: 'Buffer after (minutes)',
    notice: 'Minimum booking notice (minutes)',
    horizon: 'Booking horizon (days)',
    cutoff: 'Cancellation or rescheduling cutoff (hours before session)',
    exceptions: 'Calendar exceptions',
    available: 'Additional working time',
    unavailable: 'Blocked time',
    title: 'Title',
    kind: 'Type',
    localStart: 'Local start (Gregorian date)',
    localEnd: 'Local end (Gregorian date)',
    disambiguation: 'Repeated clock time during DST change',
    reject: 'Reject ambiguous time',
    earlier: 'First occurrence',
    later: 'Second occurrence',
    expert: 'Expert',
    service: 'Service',
    select: 'Select',
    date: 'Date (Gregorian)',
    find: 'Find available times',
    slots: 'Available times',
    hold: 'Hold this time',
    confirm: 'Confirm free booking',
    cancel: 'Cancel booking',
    reschedule: 'Reschedule',
    complete: 'Mark session completed',
    free: 'Only free services can be booked at this stage. No payment is collected.',
    expires: 'Confirmation deadline',
    remaining: 'seconds remaining',
    empty: 'No results found.',
    loading: 'Loading…',
    saved: 'Saved.',
    error: 'The operation failed. Check the information and try again.',
    conflict: 'Someone else reserved this time. Choose another time.',
    expired: 'The hold has expired.',
    cutoffError: 'The cancellation or rescheduling deadline has passed.',
    ambiguous: 'This clock time is missing or repeated. Change the time or choose an occurrence.',
    serviceUnavailable: 'This service is currently unavailable for booking.',
    policy: 'Clients may cancel or reschedule until this many hours before the session:',
    noPenalty: 'There are no monetary penalties or refunds in stage 9.',
    status: 'Status',
    period: 'Display period',
    all: 'All',
    future: 'Upcoming',
    past: 'Past',
    cancelled: 'Cancelled and expired',
    notifications: 'Booking notifications',
    read: 'Mark read',
    searchTime: 'Find experts by time',
    searchAt: 'Your desired time (Gregorian date)',
    search: 'Search',
    annual: 'Repeat every year',
    calendarType: 'Holiday date calendar',
    gregorian: 'Gregorian',
    persian: 'Persian',
    startDate: 'Start date (YYYY-MM-DD)',
    endDate: 'Inclusive end date (YYYY-MM-DD)',
    holdSeconds: 'Hold duration (seconds)',
    calendarNote:
      'Weekly hours follow the expert’s time zone. Exceptions are converted to exact UTC instants. Calendar edits do not cancel existing bookings.',
    moveNote: 'Your original reservation stays reserved until the new time is secured.',
    back: 'Back',
    next: 'Next page',
    previous: 'Previous page',
    utcOffset: 'Times are displayed in the selected time zone.',
    days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    states: {
      REQUESTED: 'Requested',
      HELD: 'Temporarily held',
      CONFIRMED: 'Confirmed',
      COMPLETED: 'Completed',
      CANCELLED: 'Cancelled',
      EXPIRED: 'Expired',
      RESCHEDULE_REQUESTED: 'Reschedule requested',
      RESCHEDULED: 'Rescheduled',
      RESCHEDULE_REJECTED: 'Reschedule failed',
      REMINDER: 'Session reminder',
    },
    pending: 'Finalizing. Refresh shortly.',
  },
});
