import { createDictionary } from './localization-runtime';
export const scholarsCopy = createDictionary('scholarsCopy', {
  fa: {
    callPolicy: 'سیاست جلسه زنده',
    recordingPolicy: 'ضبط جلسه',
    OFF: 'خاموش',
    BOTH_CONSENT: 'فقط با رضایت هر دو طرف',
    observerPolicy: 'ورود ناظر',
    NEVER: 'ممنوع',
    WITH_USER_CONSENT: 'با رضایت کاربر',
    WITH_BOTH_CONSENT: 'با رضایت هر دو طرف',
    ADMIN_EMERGENCY_ONLY: 'فقط ورود اضطراری مدیر مجاز',
    ALLOWED_BY_SERVICE_POLICY: 'مجاز مطابق شرایط این خدمت',
    retentionDays: 'مدت نگهداری ضبط (روز)',
    recordingDownload: 'اجازه دانلود ضبط برای طرفین',
    clientScreenShare: 'اجازه اشتراک صفحه به کاربر',
    application: 'درخواست استادشدن',
    professional: 'پروفایل حرفه‌ای',
    experts: 'اساتید و بررسی صلاحیت',
    applications: 'درخواست‌های جدید اساتید',
    verification: 'بررسی صلاحیت',
    taxonomy: 'تخصص‌ها، دسته‌ها و زبان‌ها',
    files: 'مدیریت فایل‌ها',
    profile: 'اطلاعات حرفه‌ای',
    documents: 'مدارک',
    specialties: 'تخصص‌ها',
    languages: 'زبان‌ها',
    services: 'خدمات و تعرفه‌ها',
    history: 'نتیجهٔ بررسی',
    save: 'ذخیره',
    create: 'ایجاد',
    submit: 'ارسال برای بررسی',
    refresh: 'به‌روزرسانی',
    remove: 'حذف',
    review: 'ثبت بررسی',
    reason: 'دلیل قابل مشاهده برای استاد',
    internal_note: 'یادداشت داخلی مدیریت',
    valid_until: 'اعتبار تأیید تا',
    name: 'نام',
    display_name: 'نام نمایشی',
    contact_phone: 'تلفن تماس (خصوصی؛ فقط برای بررسی مدیریت)',
    title: 'عنوان',
    slug: 'نشانی یکتا (حروف انگلیسی)',
    short_bio: 'معرفی کوتاه',
    biography: 'زندگی‌نامه حرفه‌ای',
    experience: 'سوابق علمی و اجرایی',
    education: 'تحصیلات',
    years: 'سال‌های تجربه',
    city: 'شهر',
    country: 'کشور',
    links: 'وب‌سایت و شبکه‌های اجتماعی (هر خط یک نشانی HTTPS)',
    visibility: 'نمایش عمومی',
    seo_title: 'عنوان موتور جستجو',
    seo_description: 'توضیح موتور جستجو',
    image_id: 'تصویر حرفه‌ای',
    select: 'انتخاب کنید',
    level: 'سطح زبان',
    viewpoints: 'موضوعات و دیدگاه‌های علمی',
    topic: 'موضوع',
    text: 'دیدگاه',
    add: 'افزودن',
    issuer: 'مؤسسه صادرکننده',
    number: 'شماره مدرک',
    issued_at: 'تاریخ صدور',
    expires_at: 'تاریخ انقضا',
    description: 'توضیحات',
    kind: 'نوع',
    public_summary: 'عنوان و مؤسسه در پروفایل عمومی نمایش داده شود (فایل همیشه خصوصی است)',
    file: 'فایل',
    upload: 'بارگذاری',
    download: 'دریافت فایل',
    status: 'وضعیت',
    missing: 'موارد ناقص',
    completion: 'درصد تکمیل',
    empty: 'موردی ثبت نشده است.',
    loading: 'در حال دریافت…',
    saved: 'ذخیره شد.',
    error: 'عملیات انجام نشد؛ اطلاعات و دسترسی را بررسی کنید.',
    scanPending: 'فایل در حال اسکن است. پس از چند لحظه به‌روزرسانی را بزنید.',
    summary: 'توضیح کوتاه',
    specialty_id: 'تخصص مرتبط',
    category_id: 'دستهٔ خدمت',
    duration_minutes: 'مدت (دقیقه؛ برای بدون مدت خالی بگذارید)',
    price_minor: 'مبلغ صحیح (ریال/تومان؛ سنت برای دلار و یورو)',
    currency: 'ارز',
    booking_required: 'نیازمند رزرو',
    terms: 'شرایط خدمت',
    publish: 'درخواست انتشار',
    disable: 'غیرفعال‌کردن',
    review_services: 'انتشار خدمت نیازمند تأیید مدیریت باشد',
    search: 'جستجوی نام، ایمیل یا شناسه',
    from: 'از تاریخ درخواست',
    to: 'تا تاریخ درخواست',
    all: 'همه',
    parent_id: 'دستهٔ والد',
    position: 'ترتیب',
    icon: 'نام آیکون',
    active: 'فعال',
    labelFa: 'عنوان فارسی',
    labelEn: 'عنوان انگلیسی',
    edit: 'ویرایش',
    back: 'بازگشت',
    owner: 'مالک',
    access: 'دسترسی',
    scan: 'اسکن',
    references: 'ارجاعات',
    size: 'حجم',
    limit: 'حداکثر حجم (بایت)',
    actions: 'عملیات',
    notifications: 'اعلان‌های پرونده',
    verified: 'استاد تأییدشده',
    publicProfile: 'پروفایل عمومی',
    applyNote: 'پس از تکمیل اطلاعات و بارگذاری مدارک سالم، پرونده را برای مدیریت ارسال کنید.',
    editNote: 'ویرایش پروفایل تأییدشده، انتشار آن را تا بررسی مجدد متوقف می‌کند.',
    noBooking: 'تعرفه‌های معرفی‌شده؛ رزرو و پرداخت در مرحلهٔ بعد فعال می‌شوند.',
    states: {
      DRAFT: 'پیش‌نویس',
      SUBMITTED: 'ارسال‌شده',
      UNDER_REVIEW: 'در حال بررسی',
      NEEDS_CHANGES: 'نیازمند اصلاح',
      APPROVED: 'تأییدشده',
      SUSPENDED: 'تعلیق‌شده',
      REJECTED: 'ردشده',
      PENDING: 'در انتظار',
      EXPIRED: 'منقضی',
      PENDING_REVIEW: 'در انتظار انتشار',
      PUBLISHED: 'منتشرشده',
      DISABLED: 'غیرفعال',
      PUBLIC: 'عمومی',
      HIDDEN: 'مخفی',
      INACTIVE: 'موقتاً غیرفعال',
      NATIVE: 'زبان مادری',
      FLUENT: 'مسلط',
      INTERMEDIATE: 'متوسط',
      CONVERSATIONAL: 'مکالمه',
      DEGREE: 'مدرک تحصیلی',
      SEMINARY: 'مدرک حوزوی',
      CERTIFICATE: 'گواهینامه تخصصی',
      LICENSE: 'مجوز حرفه‌ای',
      IDENTITY: 'مدرک هویت',
      CV: 'رزومه',
      REFERENCE: 'معرفی‌نامه',
      OTHER: 'سایر',
      TEXT: 'متنی',
      AUDIO: 'صوتی',
      VIDEO: 'تصویری',
      IN_PERSON: 'حضوری',
      QUESTION: 'پاسخ به سؤال',
      CASE_REVIEW: 'بررسی پرونده',
      TRAINING: 'آموزش',
      OWNER_ONLY: 'مالک و بررسی‌کنندهٔ مجاز',
      ADMIN_ONLY: 'فقط مدیریت مجاز',
      AUTHORIZED_USERS: 'کاربران مجاز',
      UPLOADING: 'در حال بارگذاری',
      PROCESSING: 'قرنطینه',
      SCANNING: 'در حال اسکن',
      READY: 'آماده',
      INFECTED: 'آلوده',
      DELETED: 'حذف‌شده',
      CLEAN: 'سالم',
      BLOCK: 'مسدودکردن',
      DELETE: 'حذف امن',
      QUARANTINE: 'قرنطینه',
      RESCAN: 'اسکن مجدد',
      specialty: 'تخصص',
      category: 'دسته',
      language: 'زبان',
      avatar: 'آواتار',
      image: 'تصویر',
      document: 'مدرک',
    },
  },
  en: {
    callPolicy: 'Live session policy',
    recordingPolicy: 'Recording',
    OFF: 'Off',
    BOTH_CONSENT: 'Both participants must consent',
    observerPolicy: 'Observer access',
    NEVER: 'Never',
    WITH_USER_CONSENT: 'Client consent',
    WITH_BOTH_CONSENT: 'Both participants consent',
    ADMIN_EMERGENCY_ONLY: 'Authorized emergency admin only',
    ALLOWED_BY_SERVICE_POLICY: 'Allowed under this service’s terms',
    retentionDays: 'Recording retention (days)',
    recordingDownload: 'Allow participants to download recordings',
    clientScreenShare: 'Allow client screen sharing',
    application: 'Apply to become an expert',
    professional: 'Professional profile',
    experts: 'Experts and applications',
    applications: 'New expert applications',
    verification: 'Qualification review',
    taxonomy: 'Specialties, categories and languages',
    files: 'File management',
    profile: 'Professional information',
    documents: 'Documents',
    specialties: 'Specialties',
    languages: 'Languages',
    services: 'Services and pricing',
    history: 'Review decisions',
    save: 'Save',
    create: 'Create',
    submit: 'Submit for review',
    refresh: 'Refresh',
    remove: 'Remove',
    review: 'Save review',
    reason: 'Reason visible to the expert',
    internal_note: 'Internal management note',
    valid_until: 'Verification valid until',
    name: 'Name',
    display_name: 'Display name',
    contact_phone: 'Contact phone (private; management review only)',
    title: 'Title',
    slug: 'Unique URL slug',
    short_bio: 'Short introduction',
    biography: 'Professional biography',
    experience: 'Academic and professional experience',
    education: 'Education',
    years: 'Years of experience',
    city: 'City',
    country: 'Country',
    links: 'Websites and social links (one HTTPS URL per line)',
    visibility: 'Profile visibility',
    seo_title: 'SEO title',
    seo_description: 'SEO description',
    image_id: 'Professional image',
    select: 'Select',
    level: 'Language level',
    viewpoints: 'Topics and professional views',
    topic: 'Topic',
    text: 'Professional view',
    add: 'Add',
    issuer: 'Issuing institution',
    number: 'Document number',
    issued_at: 'Issue date',
    expires_at: 'Expiry date',
    description: 'Description',
    kind: 'Type',
    public_summary: 'Show the title and institution publicly (the file always stays private)',
    file: 'File',
    upload: 'Upload',
    download: 'Download file',
    status: 'Status',
    missing: 'Missing information',
    completion: 'Completion percentage',
    empty: 'No entries yet.',
    loading: 'Loading…',
    saved: 'Saved.',
    error: 'Unable to complete the action. Check the information and your permissions.',
    scanPending: 'File scanning is in progress. Refresh after a few moments.',
    summary: 'Short description',
    specialty_id: 'Related specialty',
    category_id: 'Service category',
    duration_minutes: 'Duration (minutes; leave blank for no duration)',
    price_minor: 'Integer amount (rial/toman; cents for USD/EUR)',
    currency: 'Currency',
    booking_required: 'Requires booking',
    terms: 'Service terms',
    publish: 'Request publication',
    disable: 'Disable',
    review_services: 'Services require management approval before publication',
    search: 'Search name, email or public ID',
    from: 'Submitted from',
    to: 'Submitted until',
    all: 'All',
    parent_id: 'Parent category',
    position: 'Sort order',
    icon: 'Icon name',
    active: 'Active',
    labelFa: 'Persian label',
    labelEn: 'English label',
    edit: 'Edit',
    back: 'Back',
    owner: 'Owner',
    access: 'Access',
    scan: 'Scan',
    references: 'References',
    size: 'Size',
    limit: 'Maximum size (bytes)',
    actions: 'Actions',
    notifications: 'Application notifications',
    verified: 'Verified expert',
    publicProfile: 'Public profile',
    applyNote:
      'Complete your profile and upload clean documents, then submit your application for review.',
    editNote: 'Editing an approved profile pauses publication until it is reviewed again.',
    noBooking: 'Published rates; booking and payment will be added in the next stage.',
    states: {
      DRAFT: 'Draft',
      SUBMITTED: 'Submitted',
      UNDER_REVIEW: 'Under review',
      NEEDS_CHANGES: 'Changes requested',
      APPROVED: 'Approved',
      SUSPENDED: 'Suspended',
      REJECTED: 'Rejected',
      PENDING: 'Pending',
      EXPIRED: 'Expired',
      PENDING_REVIEW: 'Pending publication',
      PUBLISHED: 'Published',
      DISABLED: 'Disabled',
      PUBLIC: 'Public',
      HIDDEN: 'Hidden',
      INACTIVE: 'Temporarily inactive',
      NATIVE: 'Native',
      FLUENT: 'Fluent',
      INTERMEDIATE: 'Intermediate',
      CONVERSATIONAL: 'Conversational',
      DEGREE: 'Academic degree',
      SEMINARY: 'Seminary degree',
      CERTIFICATE: 'Certificate',
      LICENSE: 'Professional licence',
      IDENTITY: 'Identity document',
      CV: 'CV',
      REFERENCE: 'Reference',
      OTHER: 'Other',
      TEXT: 'Text',
      AUDIO: 'Audio',
      VIDEO: 'Video',
      IN_PERSON: 'In person',
      QUESTION: 'Question',
      CASE_REVIEW: 'Case review',
      TRAINING: 'Training',
      OWNER_ONLY: 'Owner and authorized reviewer',
      ADMIN_ONLY: 'Authorized administration only',
      AUTHORIZED_USERS: 'Authorized users',
      UPLOADING: 'Uploading',
      PROCESSING: 'Quarantined',
      SCANNING: 'Scanning',
      READY: 'Ready',
      INFECTED: 'Infected',
      DELETED: 'Deleted',
      CLEAN: 'Clean',
      BLOCK: 'Block',
      DELETE: 'Safe delete',
      QUARANTINE: 'Quarantine',
      RESCAN: 'Rescan',
      specialty: 'Specialty',
      category: 'Category',
      language: 'Language',
      avatar: 'Avatar',
      image: 'Image',
      document: 'Document',
    },
  },
});
