import { createDictionary } from './localization-runtime';
export const sessionsCopy = createDictionary('sessionsCopy', {
  en: {
    route_relay: 'Media relay verified',
    route_direct: 'Direct media route',
    route_unknown: 'Media route not yet verified',
    issue_AUDIO: 'Audio problem',
    issue_VIDEO: 'Video problem',
    issue_DISCONNECT: 'Unexpected disconnection',
    issue_JOIN: 'Trouble joining',
    issue_SCREEN_SHARE: 'Screen sharing problem',
    recording: 'Session recording',
    recordingConsent: 'I consent to recording this session.',
    recordingWithdraw: 'Withdraw recording consent',
    recordingStart: 'Start recording',
    recordingStop: 'Stop recording',
    recordingWaiting: 'Recording requires both participants’ consent.',
    recordingDownload: 'Download recording',
    recordingActive: 'Recording is active',
    recordingStopping: 'Stopping recording — waiting for confirmation',
    recordingProcessing: 'Preparing recording',
    recordingFailed: 'Recording failed',
    recordingExpired: 'Recording retention has ended',
    seconds: 'seconds',
    sessions: 'Live sessions',
    waiting: 'Waiting room',
    devices: 'Check devices',
    microphone: 'Microphone',
    camera: 'Camera',
    speaker: 'Speaker',
    preview: 'Start device preview',
    testSound: 'Test speaker',
    ready: 'Confirm device check',
    start: 'Open session',
    join: 'Join call',
    leave: 'Leave call',
    end: 'End session',
    chat: 'Session chat',
    mute: 'Toggle microphone',
    video: 'Toggle camera',
    share: 'Toggle screen sharing',
    fullscreen: 'Fullscreen',
    quality: 'Connection quality',
    poor: 'For better audio, turn off your camera.',
    help: 'Technical help',
    error: 'The action could not be completed. Check the session time, permission and connection.',
    choose: 'Choose a booking or session.',
    countdown: 'Seconds until scheduled start',
    permission:
      'Preview requests camera/microphone permission. Nothing is published until you join.',
    role: 'Role',
    CLIENT: 'Client',
    EXPERT: 'Expert',
    OBSERVER: 'Observer',
    BOOKED: 'Booked',
    WAITING_FOR_START: 'Waiting for start',
    WAITING_ROOM_OPEN: 'Waiting room open',
    JOINABLE: 'Ready to join',
    IN_SESSION: 'In session',
    ENDING: 'Ending',
    COMPLETED: 'Completed',
    CANCELLED: 'Cancelled',
    NO_SHOW_USER: 'Client absent',
    NO_SHOW_EXPERT: 'Expert absent',
    TECHNICAL_FAILURE: 'Technical failure',
    INTERRUPTED: 'Interrupted',
    TERMINATED_BY_ADMIN: 'Terminated by administrator',
    connected: 'Connected',
    disconnected: 'Disconnected',
    connecting: 'Connecting',
    reconnecting: 'Reconnecting…',
    signalReconnecting: 'Reconnecting…',
    excellent: 'Excellent',
    good: 'Good',
    poorQuality: 'Poor',
    unknown: 'Unknown',
    note: 'Session note',
    privateNote: 'Private expert note',
    sharedNote: 'Note shared with client',
    save: 'Save',
    outcome: 'Operational outcome',
    followUp: 'Follow-up required',
    feedback: 'Session feedback',
    overall: 'Overall rating',
    punctuality: 'Punctuality',
    communication: 'Communication',
    technical: 'Technical quality',
    review: 'Optional review',
    submit: 'Submit rating',
    observerRequest: 'Request observer access',
    reason: 'Reason visible to participants',
    emergency: 'Emergency access under service policy',
    admit: 'Join as authorized observer',
    allow: 'Consent',
    deny: 'Decline / revoke',
    observerWarning:
      'An observer has requested access. Their presence will be visible in the call.',
    monitor: 'Technical report',
    terminate: 'Terminate session',
    sourceNotice: 'Browser metrics are diagnostic reports; attendance is verified by LiveKit.',
    audio: 'Audio',
    text: 'Text',
    recordingOff: 'Recording is off.',
    recordingUnavailable:
      'Recording deployment and consent validation are still pending; recording is unavailable.',
    layout: 'Change video layout',
    notes: 'Notes',
    network: 'WebRTC supported',
    testPending:
      'TURN and media connectivity are verified when connecting; device check alone does not prove them.',
  },
  fa: {
    route_relay: 'عبور رسانه از رله تأیید شد',
    route_direct: 'مسیر مستقیم رسانه',
    route_unknown: 'مسیر رسانه هنوز بررسی نشده',
    issue_AUDIO: 'مشکل صدا',
    issue_VIDEO: 'مشکل تصویر',
    issue_DISCONNECT: 'قطع ناخواسته تماس',
    issue_JOIN: 'مشکل ورود به جلسه',
    issue_SCREEN_SHARE: 'مشکل اشتراک صفحه',
    recording: 'ضبط جلسه',
    recordingConsent: 'به ضبط این جلسه رضایت می‌دهم.',
    recordingWithdraw: 'پس‌گرفتن رضایت ضبط',
    recordingStart: 'شروع ضبط',
    recordingStop: 'توقف ضبط',
    recordingWaiting: 'ضبط به رضایت هر دو طرف نیاز دارد.',
    recordingDownload: 'دانلود ضبط جلسه',
    recordingActive: 'جلسه در حال ضبط است',
    recordingStopping: 'در حال توقف ضبط — منتظر تأیید',
    recordingProcessing: 'در حال آماده‌سازی ضبط',
    recordingFailed: 'ضبط ناموفق بود',
    recordingExpired: 'مهلت نگهداری ضبط تمام شده است',
    seconds: 'ثانیه',
    sessions: 'جلسات زنده',
    waiting: 'اتاق انتظار',
    devices: 'بررسی تجهیزات',
    microphone: 'میکروفون',
    camera: 'دوربین',
    speaker: 'خروجی صدا',
    preview: 'شروع پیش‌نمایش تجهیزات',
    testSound: 'تست بلندگو',
    ready: 'تأیید بررسی تجهیزات',
    start: 'باز کردن جلسه',
    join: 'ورود به تماس',
    leave: 'ترک تماس',
    end: 'پایان جلسه',
    chat: 'چت جلسه',
    mute: 'روشن/خاموش کردن میکروفون',
    video: 'روشن/خاموش کردن دوربین',
    share: 'اشتراک صفحه',
    fullscreen: 'تمام‌صفحه',
    quality: 'کیفیت اتصال',
    poor: 'برای صدای بهتر، دوربین را خاموش کنید.',
    help: 'کمک فنی',
    error: 'عملیات انجام نشد؛ زمان جلسه، مجوز و اتصال را بررسی کنید.',
    choose: 'یک رزرو یا جلسه را انتخاب کنید.',
    countdown: 'ثانیه تا شروع برنامه‌ریزی‌شده',
    permission:
      'پیش‌نمایش با اجازه دوربین و میکروفون آغاز می‌شود. تا ورود به تماس چیزی منتشر نمی‌شود.',
    role: 'نقش',
    CLIENT: 'مراجع',
    EXPERT: 'استاد',
    OBSERVER: 'ناظر',
    BOOKED: 'رزروشده',
    WAITING_FOR_START: 'در انتظار شروع',
    WAITING_ROOM_OPEN: 'اتاق انتظار باز است',
    JOINABLE: 'آماده ورود',
    IN_SESSION: 'در حال برگزاری',
    ENDING: 'در حال پایان',
    COMPLETED: 'تکمیل‌شده',
    CANCELLED: 'لغوشده',
    NO_SHOW_USER: 'عدم حضور مراجع',
    NO_SHOW_EXPERT: 'عدم حضور استاد',
    TECHNICAL_FAILURE: 'مشکل فنی',
    INTERRUPTED: 'مختل‌شده',
    TERMINATED_BY_ADMIN: 'پایان توسط مدیر',
    connected: 'متصل',
    disconnected: 'قطع‌شده',
    connecting: 'در حال اتصال',
    reconnecting: 'در حال اتصال مجدد…',
    signalReconnecting: 'در حال اتصال مجدد…',
    excellent: 'عالی',
    good: 'خوب',
    poorQuality: 'ضعیف',
    unknown: 'نامشخص',
    note: 'یادداشت جلسه',
    privateNote: 'یادداشت خصوصی استاد',
    sharedNote: 'یادداشت مشترک با مراجع',
    save: 'ذخیره',
    outcome: 'نتیجه عملیاتی',
    followUp: 'نیازمند پیگیری',
    feedback: 'ارزیابی جلسه',
    overall: 'امتیاز کلی',
    punctuality: 'وقت‌شناسی',
    communication: 'نحوه پاسخگویی',
    technical: 'کیفیت فنی',
    review: 'نظر اختیاری',
    submit: 'ثبت امتیاز',
    observerRequest: 'درخواست ورود ناظر',
    reason: 'دلیل قابل مشاهده برای طرفین',
    emergency: 'ورود اضطراری مطابق سیاست خدمت',
    admit: 'ورود به‌عنوان ناظر مجاز',
    allow: 'رضایت',
    deny: 'رد / پس‌گرفتن رضایت',
    observerWarning: 'ناظر درخواست ورود دارد؛ حضور او در تماس آشکار خواهد بود.',
    monitor: 'گزارش فنی',
    terminate: 'خاتمه جلسه',
    sourceNotice: 'شاخص مرورگر گزارش تشخیصی است؛ حضور با LiveKit بررسی می‌شود.',
    audio: 'صوتی',
    text: 'متنی',
    recordingOff: 'ضبط خاموش است.',
    recordingUnavailable: 'Recording is currently unavailable.',
    layout: 'تغییر چیدمان تصویر',
    notes: 'یادداشت‌ها',
    network: 'پشتیبانی WebRTC',
    testPending:
      'اتصال رسانه و TURN هنگام اتصال بررسی می‌شوند؛ بررسی تجهیزات به‌تنهایی تأیید آن‌ها نیست.',
  },
});
