import { createDictionary } from './localization-runtime';
export const threeCalendarCopy = createDictionary('threeCalendarCopy', {
  fa: {
    title: 'تقویم سه‌گانه',
    primary: 'تقویم اصلی',
    previous: 'ماه قبل',
    next: 'ماه بعد',
    today: 'برو به امروز',
    persian: 'شمسی',
    'islamic-umalqura': 'قمری',
    gregory: 'میلادی',
    selected: 'روز انتخاب‌شده',
    lunarNote:
      'تاریخ قمری بر پایهٔ تقویم ام‌القری است؛ رؤیت محلی هلال ممکن است یک روز تفاوت داشته باشد.',
    allDates: 'نمایش همهٔ روزها',
    selectDay: 'برای دیدن رزروها، یک روز را انتخاب کنید.',
  },
  en: {
    title: 'Three-calendar view',
    primary: 'Primary calendar',
    previous: 'Previous month',
    next: 'Next month',
    today: 'Go to today',
    persian: 'Persian',
    'islamic-umalqura': 'Hijri',
    gregory: 'Gregorian',
    selected: 'Selected day',
    lunarNote: 'Hijri dates follow Umm al-Qura; local moon sighting may differ by one day.',
    allDates: 'Show all dates',
    selectDay: 'Select a day to view its bookings.',
  },
  ar: {
    title: 'التقويم الثلاثي',
    primary: 'التقويم الرئيسي',
    previous: 'الشهر السابق',
    next: 'الشهر التالي',
    today: 'الانتقال إلى اليوم',
    persian: 'الشمسي',
    'islamic-umalqura': 'الهجري',
    gregory: 'الميلادي',
    selected: 'اليوم المحدد',
    lunarNote: 'التواريخ الهجرية وفق تقويم أم القرى؛ قد تختلف رؤية الهلال المحلية بيوم واحد.',
    allDates: 'عرض جميع الأيام',
    selectDay: 'اختر يوماً لعرض الحجوزات.',
  },
});
