export const usersCopy = {
  fa: {
    title: 'حساب من',
    loading: 'در حال دریافت اطلاعات…',
    login: 'ورود به حساب',
    logout: 'خروج',
    home: 'صفحهٔ اصلی',
    workspace: 'انتخاب فضای کاری',
    profile: 'پروفایل من',
    editProfile: 'تکمیل و ویرایش اطلاعات',
    security: 'امنیت حساب',
    publicId: 'شناسهٔ کاربری',
    displayName: 'نام نمایشی',
    avatar: 'تصویر حساب',
    presets: 'انتخاب تصویر کارتونی',
    upload: 'بارگذاری تصویر',
    imageHint: 'تصویر JPG، PNG یا WebP، حداکثر ۲ مگابایت. اطلاعات اضافی تصویر حذف می‌شود.',
    save: 'ذخیره',
    saved: 'تغییرات ذخیره شد.',
    complete: 'تکمیل اطلاعات',
    incomplete: 'برای استفاده از خدمات، اطلاعات حساب خود را تکمیل کنید.',
    completeBadge: 'اطلاعات تکمیل شده',
    next: 'مرحلهٔ بعد',
    previous: 'مرحلهٔ قبل',
    required: 'ضروری',
    private: 'فقط شما و مدیر مجاز',
    members: 'قابل نمایش به اعضای سایت',
    consent: 'با نگهداری اطلاعات پروفایل و نمایش فیلدهای مشخص‌شده به اعضای سایت موافقم.',
    withdraw: 'پس‌گرفتن رضایت نمایش پروفایل',
    consentSaved: 'انتخاب شما ثبت شد.',
    requests: 'درخواست‌های جلسه',
    requestSession: 'درخواست جلسه',
    expert: 'استاد',
    preferredDate: 'تاریخ پیشنهادی',
    submitRequest: 'ثبت درخواست',
    requestNote:
      'این درخواست برای بررسی استاد ثبت می‌شود. زمان قطعی، پرداخت و تأیید رزرو در مرحلهٔ بعد انجام می‌شود.',
    requested: 'منتظر بررسی',
    reviewed: 'بررسی شده',
    cancelled: 'لغو شده',
    cancel: 'لغو درخواست',
    review: 'ثبت بررسی',
    noRequests: 'هنوز درخواستی ثبت نشده است.',
    choose: 'انتخاب کنید',
    addOption: 'افزودن گزینه',
    removeOption: 'حذف گزینه',
    yes: 'بله',
    no: 'خیر',
    brand: 'ویانور',
    language: 'English',
    noExperts: 'هنوز استاد فعالی ثبت نشده است.',
    users: 'مدیریت کاربران',
    forms: 'فرم‌ساز پروفایل',
    organizations: 'سازمان‌ها و شعبه‌ها',
    audit: 'سوابق تغییر مجوز',
    search: 'جست‌وجو',
    searchPlaceholder: 'ایمیل یا شناسهٔ کاربر',
    email: 'ایمیل',
    invite: 'افزودن و دعوت کاربر',
    invitation: 'پیوند تعیین رمز به ایمیل کاربر ارسال می‌شود.',
    inviteAgain: 'ارسال دوبارهٔ دعوت',
    invited: 'درخواست ارسال دعوت ثبت شد.',
    roles: 'نقش‌های کاربر',
    active: 'فعال',
    disabled: 'غیرفعال',
    verified: 'ایمیل تأییدشده',
    pending: 'منتظر تأیید ایمیل',
    disable: 'غیرفعال و حذف از دسترسی',
    enable: 'فعال‌سازی',
    confirmDisable: 'دسترسی این کاربر قطع و نشست‌های او باطل شود؟ سوابق حفظ می‌شوند.',
    edit: 'ویرایش',
    back: 'بازگشت',
    addRole: 'افزودن نقش',
    removeRole: 'حذف نقش',
    scope: 'محدودهٔ دسترسی',
    platform: 'کل سامانه',
    assignForm: 'فرم تکمیل اطلاعات این کاربر',
    assign: 'تخصیص فرم',
    confirmAssign:
      'فرم کاربر عوض شود؟ پاسخ‌های قبلی در سابقه حفظ می‌شوند و کاربر باید فرم جدید را تکمیل کند.',
    newForm: 'فرم جدید',
    formTitle: 'عنوان فرم',
    persian: 'فارسی',
    english: 'انگلیسی',
    layout: 'نمایش فرم',
    tabs: 'تب‌ها',
    steps: 'مراحل',
    newSection: 'افزودن بخش',
    sectionTitle: 'عنوان بخش',
    deleteSection: 'حذف بخش',
    fieldPalette: 'افزودن فیلد',
    fieldSettings: 'تنظیمات فیلد',
    fieldLabel: 'عنوان فیلد',
    deleteField: 'حذف فیلد',
    moveUp: 'انتقال به بالا',
    moveDown: 'انتقال به پایین',
    options: 'گزینه‌ها',
    optionHint: 'هر خط: مقدار | عنوان فارسی | عنوان انگلیسی',
    min: 'حداقل عدد',
    max: 'حداکثر عدد',
    condition: 'نمایش مشروط',
    always: 'همیشه نمایش داده شود',
    equals: 'برابر با',
    draft: 'پیش‌نویس',
    published: 'منتشرشده',
    publish: 'انتشار فرم',
    publishConfirm:
      'نسخهٔ جدید فرم منتشر شود؟ کاربران باید اطلاعات خود را با این نسخه به‌روز کنند.',
    preview: 'پیش‌نمایش فرم',
    editor: 'ویرایش فرم',
    noFields: 'از فهرست ابزارها یک فیلد اضافه کنید.',
    version: 'نسخه',
    defaultForm: 'فرم پیش‌فرض همهٔ کاربران',
    organizationName: 'نام سازمان یا شعبه',
    parent: 'سازمان بالادست',
    independent: 'سازمان مستقل',
    createOrganization: 'ایجاد سازمان / شعبه',
    noData: 'اطلاعاتی برای نمایش وجود ندارد.',
    profileLink: 'مشاهدهٔ پروفایل',
    client: 'مراجع',
    date: 'تاریخ',
    status: 'وضعیت',
    actions: 'عملیات',
    roleReady:
      'این فضای کاری بر اساس مجوز واقعی شما فعال است. ابزارهای تخصصی این نقش در مراحل مربوط به خود اضافه می‌شوند.',
    denied: 'به این فضای کاری دسترسی ندارید.',
    retry: 'تلاش دوباره',
    errors: {
      UNAVAILABLE: 'ارتباط با سرویس برقرار نشد. دوباره تلاش کنید.',
      UNAUTHORIZED: 'نشست شما پایان یافته؛ دوباره وارد شوید.',
      FORBIDDEN: 'اجازهٔ انجام این کار را ندارید.',
      INVALID_INPUT: 'اطلاعات واردشده معتبر نیست.',
      INVALID_ANSWERS: 'پاسخ یکی از فیلدها معتبر نیست.',
      PROFILE_INCOMPLETE: 'فیلدهای ضروری پروفایل را تکمیل کنید.',
      CONSENT_REQUIRED: 'ابتدا رضایت مربوط به پروفایل را ثبت کنید.',
      CONFLICT: 'اطلاعات هم‌زمان تغییر کرده است؛ دوباره بارگذاری کنید.',
      FORM_CHANGED: 'نسخهٔ فرم تغییر کرده است؛ دوباره بارگذاری کنید.',
      ACCOUNT_EXISTS: 'این ایمیل قبلاً ثبت شده است.',
      LAST_ADMIN: 'آخرین مدیر کل را نمی‌توان حذف کرد.',
      REMOVE_ADMIN_FIRST: 'ابتدا نقش مدیر کل این کاربر را حذف کنید.',
      INVALID_IMAGE: 'تصویر معتبر نیست یا اندازهٔ آن بیش از حد مجاز است.',
      IMAGE_LIMIT: 'سهمیهٔ بارگذاری تصویر پر شده است.',
      DUPLICATE_REQUEST: 'درخواست مشابه ثبت شده یا درخواست‌ها بیش از حد نزدیک‌اند.',
      EXPERT_UNAVAILABLE: 'این استاد در حال حاضر در دسترس نیست.',
      FORM_NOT_PUBLISHED: 'ابتدا فرم را منتشر کنید.',
      ACCOUNT_DISABLED: 'حساب غیرفعال است.',
      NOT_FOUND: 'اطلاعات پیدا نشد.',
    },
    roleNames: {
      account: 'مراجع',
      expert: 'استاد و مشاور',
      secretary: 'منشی',
      responder: 'پاسخ‌گو',
      scientific: 'مدیر علمی',
      support: 'پشتیبانی',
      finance: 'مالی',
      content: 'مدیر محتوا',
      organization: 'مدیر سازمان',
      admin: 'مدیر کل',
      ai: 'هوش مصنوعی',
      call: 'مرکز تماس',
      operations: 'عملیات',
      auditor: 'حسابرس',
    },
    fieldTypes: {
      text: 'متن کوتاه',
      textarea: 'متن بلند',
      number: 'عدد',
      email: 'ایمیل',
      phone: 'تلفن',
      url: 'نشانی وب',
      date: 'تاریخ',
      select: 'فهرست کشویی',
      radio: 'تک‌انتخابی',
      checkbox: 'تأیید / انتخاب',
      multiselect: 'چندانتخابی',
      image: 'بارگذاری تصویر',
      heading: 'عنوان و توضیح',
    },
  },
  en: {
    title: 'My account',
    loading: 'Loading…',
    login: 'Sign in',
    logout: 'Sign out',
    home: 'Home',
    workspace: 'Choose workspace',
    profile: 'My profile',
    editProfile: 'Complete and edit profile',
    security: 'Account security',
    publicId: 'User ID',
    displayName: 'Display name',
    avatar: 'Account image',
    presets: 'Choose a cartoon avatar',
    upload: 'Upload image',
    imageHint: 'JPG, PNG or WebP, up to 2 MB. Image metadata is removed.',
    save: 'Save',
    saved: 'Changes saved.',
    complete: 'Complete profile',
    incomplete: 'Complete your profile to use services.',
    completeBadge: 'Profile complete',
    next: 'Next step',
    previous: 'Previous step',
    required: 'Required',
    private: 'Only you and authorized administrators',
    members: 'Visible to signed-in members',
    consent: 'I agree to profile data storage and sharing the marked fields with site members.',
    withdraw: 'Withdraw profile sharing consent',
    consentSaved: 'Your choice was recorded.',
    requests: 'Session requests',
    requestSession: 'Request a session',
    expert: 'Expert',
    preferredDate: 'Preferred date',
    submitRequest: 'Submit request',
    requestNote:
      'This request is submitted for expert review. Confirmed scheduling, payment and booking confirmation follow in a later stage.',
    requested: 'Awaiting review',
    reviewed: 'Reviewed',
    cancelled: 'Cancelled',
    cancel: 'Cancel request',
    review: 'Mark reviewed',
    noRequests: 'No requests yet.',
    choose: 'Choose an option',
    addOption: 'Add option',
    removeOption: 'Remove option',
    yes: 'Yes',
    no: 'No',
    brand: 'Vianoor',
    language: 'فارسی',
    noExperts: 'No active experts have been added yet.',
    users: 'User management',
    forms: 'Profile form builder',
    organizations: 'Organizations and branches',
    audit: 'Permission history',
    search: 'Search',
    searchPlaceholder: 'Email or user ID',
    email: 'Email',
    invite: 'Add and invite user',
    invitation: 'A password setup link will be emailed to the user.',
    inviteAgain: 'Resend invitation',
    invited: 'Invitation queued.',
    roles: 'User roles',
    active: 'Active',
    disabled: 'Disabled',
    verified: 'Email verified',
    pending: 'Awaiting email verification',
    disable: 'Disable access',
    enable: 'Enable account',
    confirmDisable:
      'Disable this account and revoke its sessions? Historical records will be preserved.',
    edit: 'Edit',
    back: 'Back',
    addRole: 'Add role',
    removeRole: 'Remove role',
    scope: 'Access scope',
    platform: 'Entire platform',
    assignForm: 'Assigned profile form',
    assign: 'Assign form',
    confirmAssign:
      'Change the assigned form? Previous answers are preserved in history and the user must complete the new form.',
    newForm: 'New form',
    formTitle: 'Form title',
    persian: 'Persian',
    english: 'English',
    layout: 'Form layout',
    tabs: 'Tabs',
    steps: 'Steps',
    newSection: 'Add section',
    sectionTitle: 'Section title',
    deleteSection: 'Delete section',
    fieldPalette: 'Add a field',
    fieldSettings: 'Field settings',
    fieldLabel: 'Field label',
    deleteField: 'Delete field',
    moveUp: 'Move up',
    moveDown: 'Move down',
    options: 'Options',
    optionHint: 'One per line: value | Persian label | English label',
    min: 'Minimum number',
    max: 'Maximum number',
    condition: 'Conditional visibility',
    always: 'Always visible',
    equals: 'Equals',
    draft: 'Draft',
    published: 'Published',
    publish: 'Publish form',
    publishConfirm:
      'Publish a new version? Users will need to update their profile for this version.',
    preview: 'Preview form',
    editor: 'Edit form',
    noFields: 'Add a field from the toolbox.',
    version: 'Version',
    defaultForm: 'Default form for all users',
    organizationName: 'Organization or branch name',
    parent: 'Parent organization',
    independent: 'Independent organization',
    createOrganization: 'Create organization / branch',
    noData: 'Nothing to display.',
    profileLink: 'View profile',
    client: 'Client',
    date: 'Date',
    status: 'Status',
    actions: 'Actions',
    roleReady:
      'This workspace reflects your actual permissions. Specialized tools will be added in their corresponding stages.',
    denied: 'You do not have access to this workspace.',
    retry: 'Try again',
    errors: {
      UNAVAILABLE: 'The service could not be reached. Please retry.',
      UNAUTHORIZED: 'Your session has ended. Sign in again.',
      FORBIDDEN: 'You do not have permission for this action.',
      INVALID_INPUT: 'Please check the entered information.',
      INVALID_ANSWERS: 'A field answer is invalid.',
      PROFILE_INCOMPLETE: 'Complete the required profile fields.',
      CONSENT_REQUIRED: 'Record your profile consent first.',
      CONFLICT: 'The data changed concurrently. Reload and try again.',
      FORM_CHANGED: 'The form version changed. Reload and try again.',
      ACCOUNT_EXISTS: 'This email is already registered.',
      LAST_ADMIN: 'The last platform administrator cannot be removed.',
      REMOVE_ADMIN_FIRST: 'Remove this account’s administrator role first.',
      INVALID_IMAGE: 'The image is invalid or too large.',
      IMAGE_LIMIT: 'The image upload limit has been reached.',
      DUPLICATE_REQUEST: 'A similar request exists or requests were submitted too quickly.',
      EXPERT_UNAVAILABLE: 'This expert is not currently available.',
      FORM_NOT_PUBLISHED: 'Publish the form first.',
      ACCOUNT_DISABLED: 'This account is disabled.',
      NOT_FOUND: 'The requested information was not found.',
    },
    roleNames: {
      account: 'Client',
      expert: 'Expert',
      secretary: 'Secretary',
      responder: 'Responder',
      scientific: 'Scientific manager',
      support: 'Support',
      finance: 'Finance',
      content: 'Content manager',
      organization: 'Organization manager',
      admin: 'Administrator',
      ai: 'AI',
      call: 'Call center',
      operations: 'Operations',
      auditor: 'Auditor',
    },
    fieldTypes: {
      text: 'Short text',
      textarea: 'Long text',
      number: 'Number',
      email: 'Email',
      phone: 'Phone',
      url: 'Web address',
      date: 'Date',
      select: 'Dropdown',
      radio: 'Radio buttons',
      checkbox: 'Checkbox',
      multiselect: 'Multiple choices',
      image: 'Image upload',
      heading: 'Heading',
    },
  },
} as const;
